AutoPas/AutoPas

src/AutoPas.h
src/cells/RMMParticleCell2T.h
src/containers/DirectSum.h
src/containers/LinkedCells.h
src/containers/ParticleContainer.h
src/iterators/SingleCellIterator.h
src/pairwiseFunctors/CellFunctor.h
src/sph/SPHCalcHydroForceFunctor.h
tests/testAutopas/AoSvsSoATest.cpp
tests/testAutopas/CMakeLists.txt
tests/testAutopas/Newton3OnOffTest.cpp
tests/testAutopas/Newton3OnOffTest.h
tests/testAutopas/SPHTest.cpp
tests/testAutopas/mocks/MockFunctor.h

closes #5
* non-newton 3 functors are now possible.
* tested and documented

non newton3 force calculation

---

Jenkinsfile

makes jenkins tests parallel to make it easier to figure out, what's going wrong

jenkins test in parallel

---

Jenkinsfile
cmake/modules/clang-format.cmake

adds formatting checker to jenkins

jenkins check formatting

---

Jenkinsfile
cmake/modules/other-compileroptions.cmake

Parses compiler warnings in jenkins.
* enables fast_math by default

compiler warnings read in jenkins

---

README.md
examples/sph/sph-main.cpp
src/autopas/containers/DirectSum.h
src/autopas/containers/LinkedCells.h
src/autopas/containers/VerletLists.h
src/autopas/iterators/ParticleIterator.h
src/autopas/utils/WrapOpenMP.h
tests/testAutopas/ParticleIteratorTest.cpp
tests/testAutopas/ParticleIteratorTest.h

Openmp iterators

---

src/autopas/AutoPas.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/ContainerSelector.h

resolves #75 by updating the respective pointers and removing the one in AutoPas.h that is a potential source for future mistakes.

Fixing container pointer

---

examples/md-flexible/MDFlexParser.cpp
examples/md-flexible/MDFlexParser.h
examples/md-flexible/main.cpp
src/autopas/containers/VerletListHelpers.h
src/autopas/containers/VerletLists.h
src/autopas/pairwiseFunctors/FlopCounterFunctor.h

FlopCounter.SoAFunctor(verlet)

---

Jenkinsfile
README.md

This adds two tests to the jenkins:
* intel compiler without openmp
* intel compiler with openmp

Intel Compiler in Jenkins

---

Jenkinsfile
tests/testAutopas/ParticleIteratorTest.cpp

closes #76:
examples are run with sanitizers.

test examples with sanitizers

---

CMakeLists.txt
README.md
examples/md-flexible/MDFlexParser.cpp
examples/md-flexible/main.cpp
examples/md/md-main.cpp
examples/sph-verlet/sph-main-verlet.cpp
src/autopas/AutoPas.h
src/autopas/containers/CellBlock3D.h
src/autopas/containers/LinkedCells.h
src/autopas/containers/ParticleContainer.h
src/autopas/containers/VerletLists.h
src/autopas/iterators/ParticleIterator.h
src/autopas/pairwiseFunctors/LJFunctor.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/ContainerSelector.h
src/autopas/selectors/TraversalSelector.h
src/autopas/utils/ExceptionHandler.h
src/autopas/utils/Logger.h
src/autopas/utils/MemoryProfiler.cpp
tests/testAutopas/AutoTunerTest.cpp
tests/testAutopas/ExceptionHandlerTest.cpp
tests/testAutopas/LoggerTest.cpp
tests/testAutopas/LoggerTest.h

New macros for logging that support way more verbose output.
Resolves #87

Verbose log

---

cmake/modules/other-compileroptions.cmake
src/autopas/containers/DirectSum.h
tests/testAutopas/DirectSumTest.cpp
tests/testAutopas/LinkedCellsTest.cpp

adds unit test for LinkedCells' and DirectSum's UpdateContainer  very close to boundary

---

tests/testAutopas/LJFunctorTest.cpp
tests/testAutopas/LJFunctorTest.h

code deduplication LJ Functor test

---

CMakeLists.txt
Jenkinsfile
cmake/modules/OpenMP.cmake
cmake/modules/logging.cmake
cmake/modules/other-compileroptions.cmake
cmake/modules/vectorization.cmake
examples/md-flexible/CMakeLists.txt
examples/md-flexible/main.cpp
examples/md/md-main.cpp
libs/CMakeLists.txt
src/autopas/CMakeLists.txt
src/autopas/utils/SoA.h
tests/testAutopas/LJFunctorTest.cpp

Please include a summary of the changes.

Tending to c make

---

examples/md-flexible/strongscaling.sh
src/autopas/pairwiseFunctors/LJFunctor.h
src/autopas/sph/SPHCalcDensityFunctor.h
src/autopas/sph/SPHCalcHydroForceFunctor.h
tests/testAutopas/LJFunctorTest.cpp
tests/testAutopas/LJFunctorTest.h

adds calculation of global values to ljfunctor's soa functor
- #102 
- #113 

adds calculation of global values to ljfunctor's soa functor

---

examples/md-flexible/CMakeLists.txt
examples/md-flexible/MDFlexParser.cpp
examples/md-flexible/MDFlexParser.h
examples/md-flexible/main.cpp
examples/md-flexible/measurePerf.sh
examples/md-flexible/plotScript.gp

Faster measure perf

---

examples/md-flexible/MDFlexParser.cpp
examples/md-flexible/MDFlexParser.h
examples/md-flexible/main.cpp
src/autopas/AutoPas.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/TraversalSelector.h
tests/testAutopas/AutoTunerTest.cpp
tests/testAutopas/Newton3OnOffTest.cpp

Lots of options that were introduced recently were not accessible from the high level interface.

Making options usable

---

src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/cellPairTraversals/TraversalInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/options/ContainerOptions.h
src/autopas/options/DataLayoutOptions.h
src/autopas/options/SelectorStrategies.h
src/autopas/options/TraversalOptions.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/ContainerSelector.h
src/autopas/selectors/TraversalSelector.h
src/autopas/utils/StringUtils.h
tests/testAutopas/tests/utils/StringUtilsTest.h

Options directory

---

src/autopas/containers/ParticleContainer.h
src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/linkedCells/traversals/C01Traversal.h
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp

add c01 and c18 to linkedcells traversals

---

src/autopas/containers/linkedCells/traversals/C01Traversal.h

Wrong condition for exception in traverseCellPairs is fixed.

c01 fix exception in traverseCellPairs

---

examples/md-flexible/MDFlexParser.cpp
examples/md-flexible/MDFlexParser.h
examples/md-flexible/main.cpp
src/autopas/AutoPas.h

AutoPas now supports logging to files.
Also md-flex via
```
md-flex --log-file logFileName.log
```

Choose log stream

---

src/autopas/AutoPas.h

Simplified initialization of the logger such that using file loggers per mpi ranks works.
tested with mardyn

reworked init of logger

---

src/autopas/utils/Timer.cpp
src/autopas/utils/Timer.h
tests/testAutopas/tests/utils/TimerTest.cpp

Update Timer from ctime to std::chrono
tested with TimerTest

Update Timer from ctime to std::chrono

---

docs/Doxyfile.in
tests/testAutopas/testingHelpers/GaussianGenerator.h
tests/testAutopas/testingHelpers/GridGenerator.h
tests/testAutopas/testingHelpers/RandomGenerator.h
tests/testAutopas/testingHelpers/commonTypedefs.h

Testing helpers are used in examples and should be documented
`make doc_doxygen -j12 | grep -i warning`

Doc for helpers

---

Jenkinsfile

Parallelizes cuda with default build. For that squashing the other stages was useful to reduce code duplication.
Does anyone know a better way to specify the different stages? 
- cuda stage introduced in #177 

Parallelize default and cuda build

---

src/autopas/AutoPas.h
src/autopas/autopasIncludes.h
src/autopas/cells/FullParticleCell.h
src/autopas/cells/RMMParticleCell2T.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/particles/Particle.h
src/autopas/utils/AutoPasMacros.h
tests/testAutopas/mocks/MockVerletLists.h
tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
tests/testAutopas/tests/containers/directSum/DirectSumContainerTest.cpp
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp

Adapts change of updateContainer function, i.e., they now return a vector of invalid particles.
- part of #215

adapt updateContainer interface change

---

CMakeLists.txt
cmake/modules/CodeCoverage.cmake
cmake/modules/coloring.cmake

Small things I just stumbled upon:

Coloring.cmake with generator expressions.

---

src/autopas/utils/MemoryProfiler.cpp

Rewrote Memory profiler with Cpp style file access.
The previous implementation leaked file descriptors which could result in segfaults.

MemProfiler Cpp style

---

examples/sphDiagramGeneration/sph-diagram-generation.cpp
src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
src/autopas/containers/cellPairTraversals/CBasedTraversal.h
src/autopas/containers/cellPairTraversals/CellPairTraversal.h
src/autopas/containers/cellPairTraversals/DummyTraversal.h
src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
src/autopas/containers/cellPairTraversals/TraversalInterface.h
src/autopas/containers/directSum/DirectSumTraversal.h
src/autopas/containers/linkedCells/traversals/C01CudaTraversal.h
src/autopas/containers/linkedCells/traversals/C01Traversal.h
src/autopas/containers/linkedCells/traversals/C08Traversal.h
src/autopas/containers/linkedCells/traversals/C18Traversal.h
src/autopas/containers/linkedCells/traversals/SlicedTraversal.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/containers/verletListsCellBased/verletLists/traversals/TraversalVerlet.h
src/autopas/containers/verletListsCellBased/verletLists/traversals/VerletTraversalInterface.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C01TraversalVerlet.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C18TraversalVerlet.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/SlicedTraversalVerlet.h
src/autopas/options/Newton3Option.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/TraversalSelector.h
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
tests/testAutopas/tests/pairwiseFunctors/FlopCounterTest.cpp
tests/testAutopas/tests/selectors/AutoTunerTest.cpp

Traversal interface rework

---

src/autopas/containers/CellBlock3D.h
src/autopas/containers/CellBorderAndFlagManager.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/directSum/DirectSumTraversal.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/linkedCells/traversals/C01Traversal.h
src/autopas/containers/linkedCells/traversals/C08CellHandler.h
src/autopas/containers/linkedCells/traversals/C18Traversal.h
src/autopas/iterators/ParticleIterator.h
src/autopas/iterators/ParticleIteratorInterface.h
src/autopas/iterators/RegionParticleIterator.h
src/autopas/iterators/SingleCellIterator.h
src/autopas/iterators/SingleCellIteratorInterface.h
src/autopas/namespaces.h
src/autopas/pairwiseFunctors/CellFunctor.h
tests/testAutopas/testingHelpers/commonTypedefs.h
tests/testAutopas/tests/containers/CellBlock3DTest.cpp
tests/testAutopas/tests/containers/CellBlock3DTest.h

Remove inline for namespaces

---

src/autopas/containers/ParticleContainer.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h

replace ParticleContainer::_applicableTraversals by compatibleTraversals::allCompatibleTraversals(this->getContainerType())

replace ParticleContainer::_applicableTraversals

---

tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp

Remove code duplication in ContainerSelectorTest and correct calculation of halo box. Before, not all faces of the halo box were tested.

ContainerSelectorTest: Refactoring and bug fixing

---

src/autopas/cells/FullParticleCell.h
src/autopas/cells/ParticleCell.h
src/autopas/cells/RMMParticleCell2T.h

Made parameter of ParticleCell::addParticle() const. Added const [] operator to FullParticleCell. Removed unnecessary virtual.
None
None
Jenkins

Small constness improvement

---

src/autopas/containers/linkedCells/traversals/C18Traversal.h
src/autopas/utils/ArrayMath.h
tests/testAutopas/tests/utils/ArrayMathTest.cpp

* replace class `ArrayMath` by namespace `ArrayMath`
* make all functions `constexpr`
* add cast function `static_cast_array`

ArrayMath: Refactoring, new function static_cast_array

---

src/autopas/utils/ThreeDimensionalMapping.h

ThreeDimensionalMapping:
* make functions `constexpr`
* improve type safety by adding `static_assert`
* correct comments

ThreeDimensionalMapping: Refactoring

---

.github/CONTRIBUTING.md

Add StringUtilsTest to contribution guidelines for adding traversals and containers.
None
None
Just added a new traversal on my own and that was necessary.

Add StringUtilsTest to contribution guidelines for adding things

---

src/autopas/iterators/ParticleIterator.h
src/autopas/iterators/RegionParticleIterator.h
src/autopas/iterators/SingleCellIterator.h
src/autopas/namespaces.h
src/autopas/utils/ArrayMath.h
src/autopas/utils/CudaDeviceVector.h
src/autopas/utils/CudaExceptionHandler.h
src/autopas/utils/CudaSoAType.h
src/autopas/utils/CudaStreamHandler.h
src/autopas/utils/DataLayoutConverter.h
src/autopas/utils/ExceptionHandler.h
src/autopas/utils/MemoryProfiler.h
src/autopas/utils/ParticleCellHelpers.h
src/autopas/utils/SoAStorage.h
src/autopas/utils/SoAType.h
src/autopas/utils/StringUtils.h
src/autopas/utils/ThreeDimensionalMapping.h
src/autopas/utils/Timer.h
src/autopas/utils/inBox.h

- nested namespaced
- using constexpr if instead of enable_if in SoAStorage

Adds more c++17 features

---

.github/CONTRIBUTING.md

A description of where to find the docker stuff and how to use it.
Or should we move this to the Readme?

how to use the docker containers

---

src/autopas/iterators/SingleCellIterator.h

Simplifies SingleCellIterator::operator*.
None
None
Jenkins

Simplify SingleCellIterator::operator*

---

src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h

This PR fixes a bug in C04SoA Traversal.
- #301

C04SoA: Bug fix

---

src/autopas/namespaces.h

Add missing namespaces to namespaces.h

---

docs/C08TraversalScheme.py
examples/md-flexible/plotScript.gp
src/autopas/AutoPas.h
src/autopas/LogicHandler.h
src/autopas/cells/FullParticleCell.h
src/autopas/containers/CellBlock3D.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/verletLists/VarVerletLists.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
src/autopas/iterators/ParticleIterator.h
src/autopas/iterators/RegionParticleIterator.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/ContainerSelector.h
src/autopas/selectors/OptimumSelector.h
src/autopas/selectors/tuningStrategy/BayesianSearch.h
src/autopas/selectors/tuningStrategy/FullSearch.h
src/autopas/selectors/tuningStrategy/TuningStrategyInterface.h
src/autopas/sph/SPHCalcHydroForceFunctor.h
src/autopas/sph/SPHKernels.h
src/autopas/utils/ArrayMath.h
tests/testAutopas/tests/utils/ArrayMathTest.cpp

This PR implements various small refactoring tasks and enhancements:
- ArrayMath: 2 new functions to compute the L2Norm and the product of all elements in a container
- declare more attributes and methods `const`
- remove redundant assignments 
- plotScript: Display numbers as power of 2
- DirectSum: replace return by pointer with return by ref

Refactoring

---

examples/sphDiagramGeneration/CMakeLists.txt
examples/sphDiagramGeneration/measurePerf.sh
examples/sphDiagramGeneration/sph-diagram-generation.cpp

Adapts sph-diagram-generation to AutoPas interface and adapts measurePerf.sh script accordingly

adapts sph-diagram-generation to AutoPas interface

---

.github/CONTRIBUTING.md

mention cmake format in CONTRIBUTING.md and how to use it

Document CMake Format

---

src/autopas/selectors/tuningStrategy/GaussianProcess.h
tests/testAutopas/tests/selectors/tuningStrategy/BayesianSearchTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianProcessTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianProcessTest.h

- this stuff was introduced in #363

Refactor baysian tests

---

examples/md-flexible/Simulation.h
examples/md-flexible/Thermostat.h
examples/md-flexible/input/AllOptions.yaml
examples/md-flexible/parsing/MDFlexConfig.cpp
examples/md-flexible/parsing/MDFlexConfig.h
examples/md-flexible/parsing/YamlParser.cpp
examples/md-flexible/parsing/YamlParser.h
examples/md-flexible/tests/ThermostatTest.cpp
examples/md-flexible/tests/ThermostatTest.h

stateless Thermostat

---

examples/md-flexible/Simulation.h
examples/md-flexible/tests/ParticlePropertiesLibraryTest.cpp
examples/md-flexible/tests/ParticlePropertiesLibraryTest.h
examples/md-flexible/tests/ThermostatTest.h
examples/md-flexible/tests/TimeDiscretizationTest.h
src/autopas/molecularDynamics/LJFunctor.h
src/autopas/molecularDynamics/LJFunctorAVX.h
src/autopas/molecularDynamics/ParticlePropertiesLibrary.h
tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
tests/testAutopas/tests/pairwiseFunctors/LJFunctorAVXTest.cpp
tests/testAutopas/tests/pairwiseFunctors/LJFunctorAVXTest.h
tests/testAutopas/tests/pairwiseFunctors/LJFunctorTest.cpp
tests/testAutopas/tests/pairwiseFunctors/LJFunctorTest.h

Shift is a Particle Property

---

Jenkinsfile
cmake/modules/ccache.cmake

- enable ccache for all Jenkins builds.

Jenkins: enable ccache

---

Jenkinsfile

Fixes Jenkins build by adding entrypoint.sh (resp. uid_entrypoint for intel) to sh commands

Jenkins HOTFIX

---

examples/md-flexible/Simulation.h

Removed some unnecessary variables and use config object directly.

fixed initialization of autopas object

---

examples/md-flexible/Thermostat.h

Minor fixes to the doc in Thermostat.h

Thermostat doc fixes

---

src/autopas/containers/verletClusterLists/VerletClusterCells.h
src/autopas/containers/verletClusterLists/VerletClusterCellsParticleIterator.h
tests/testAutopas/tests/autopasInterface/IteratorTest.cpp
tests/testAutopas/tests/autopasInterface/IteratorTest.h

Enables proper OpenMP support for:
- #395 

verlet cluster cells iterator open mp fix398

---

examples/md-flexible/parsing/MDFlexConfig.cpp

also write vtk write frequency to std out and yaml file.

also write vtk write frequency

---

src/autopas/molecularDynamics/LJFunctorAVX.h

removed union workaround in intrinsics code.

removed union workaround

---

src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
src/autopas/molecularDynamics/LJFunctor.h
src/autopas/molecularDynamics/LJFunctorAVX.h
src/autopas/pairwiseFunctors/FlopCounterFunctor.h
src/autopas/pairwiseFunctors/Functor.h
src/autopas/sph/SPHCalcDensityFunctor.h
src/autopas/sph/SPHCalcHydroForceFunctor.h

removes some useless `const`s

---

.github/CONTRIBUTING.md

Update one of the tests that have to be extended when adding a new Traversal in CONTRIBUTING.md

Update Adding a new Traversal in CONTRIBUTING.md

---

src/autopas/selectors/tuningStrategy/ActiveHarmony.h

When defining allowedCellSizeFactors as real, the step size was calculated wrong.

Harmony bugfix

---

src/autopas/selectors/TraversalSelector.h
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp

Skip tests that are skipped

---

src/autopas/AutoPas.h
src/autopas/containers/CompatibleTraversals.h
tests/testAutopas/testingHelpers/EmptyFunctor.h

afaik this is not true anymore?

removed outdated comment

---

examples/md-flexible/parsing/MDFlexConfig.h
src/autopas/AutoPas.h
src/autopas/options/AcquisitionFunctionOption.h
src/autopas/selectors/tuningStrategy/BayesianClusterSearch.h
src/autopas/selectors/tuningStrategy/BayesianSearch.h
src/autopas/selectors/tuningStrategy/GaussianModel/AcquisitionFunction.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianCluster.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianHyperparameters.cpp
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianHyperparameters.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianProcess.h
tests/testAutopas/tests/options/OptionTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/BayesianClusterSearchTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/BayesianClusterSearchTest.h
tests/testAutopas/tests/selectors/tuningStrategy/BayesianSearchTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianClusterTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianClusterTest.h
tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianProcessTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianProcessTest.h
tests/testAutopas/tests/selectors/tuningStrategy/TuningStrategyTest.cpp

- Restricted Gaussian models to maximization problems
- GaussianCluster: generate Hyperparameter globally across Clusters

Bayes discrete fix

---

examples/md-flexible/src/parsing/CLIParser.h
examples/md-flexible/src/parsing/MDFlexConfig.h

make zsh suggest the correct files for arguments that take files

Filename completions

---

examples/md-flexible/src/parsing/MDFlexConfig.h
src/autopas/options/LoadEstimatorOption.h
src/autopas/selectors/FeatureVector.h
src/autopas/selectors/FeatureVectorEncoder.h
src/autopas/selectors/tuningStrategy/BayesianClusterSearch.h
src/autopas/selectors/tuningStrategy/BayesianSearch.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianProcess.h
src/autopas/selectors/tuningStrategy/TuningStrategyFactory.cpp
tests/testAutopas/tests/selectors/FeatureVectorTest.cpp
tests/testAutopas/tests/selectors/FeatureVectorTest.h
tests/testAutopas/tests/selectors/tuningStrategy/BayesianClusterSearchTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/TuningStrategyTest.cpp

- Refactored encoding functions of FeatureVector to FeatureVectorEncoder.
- Combined Container, Traversal and LoadEstimator as one tunable dimension.

Refactored encoding of FeatureVectors

---

src/autopas/AutoPas.h
src/autopas/containers/verletClusterLists/Cluster.h
src/autopas/containers/verletClusterLists/ClusterTower.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletClusterLists/VerletClusterListsRebuilder.h
src/autopas/containers/verletClusterLists/traversals/ClusterFunctor.h
src/autopas/containers/verletClusterLists/traversals/VerletClustersColoringTraversal.h
src/autopas/containers/verletClusterLists/traversals/VerletClustersStaticTraversal.h
src/autopas/containers/verletClusterLists/traversals/VerletClustersTraversal.h
src/autopas/containers/verletClusterLists/traversals/VerletClustersTraversalInterface.h
src/autopas/selectors/ContainerSelector.h
src/autopas/selectors/TraversalSelector.h
tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.cpp
tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.h
tests/testAutopas/tests/containers/verletClusterLists/VerletClusterTowerTest.cpp

Variable cluster size

---

src/autopas/containers/verletClusterCells/VerletClusterCells.h
src/autopas/containers/verletClusterCells/VerletClusterCellsParticleIterator.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/verletLists/VarVerletLists.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/containers/verletListsCellBased/verletLists/neighborLists/VerletNeighborListInterface.h
src/autopas/containers/verletListsCellBased/verletLists/neighborLists/asBuild/VerletNeighborListAsBuild.h
src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
src/autopas/iterators/ParticleIterator.h

Fixes doxygen warnings for version 1.8.18

fixes doxygen warnings for version 1.8.18

---

docs/Doxyfile.in
src/autopas/molecularDynamics/LJFunctor.h
src/autopas/molecularDynamics/LJFunctorAVX.h
src/autopas/molecularDynamics/LJFunctorCuda.cu
src/autopas/molecularDynamics/LJFunctorCuda.cuh
src/autopas/molecularDynamics/LJFunctorCudaConstants.cuh
src/autopas/molecularDynamics/LJFunctorCudaGlobals.cu
src/autopas/molecularDynamics/LJFunctorCudaGlobals.cuh
src/autopas/molecularDynamics/MoleculeLJ.h
src/autopas/pairwiseFunctors/Functor.h
src/autopas/pairwiseFunctors/FunctorCuda.cuh
src/autopas/particles/OwnershipState.h
src/autopas/particles/ParticleBase.h
tests/testAutopas/testingHelpers/EmptyFunctor.h
tests/testAutopas/tests/containers/TraversalComparison.cpp
tests/testAutopas/tests/containers/TraversalComparison.h
tests/testAutopas/tests/molecularDynamics/AoSvsCudaTest.cpp
tests/testAutopas/tests/molecularDynamics/AoSvsCudaTest.h
tests/testAutopas/tests/molecularDynamics/LJFunctorCudaTest.cpp
tests/testAutopas/tests/molecularDynamics/LJFunctorCudaTest.h

Fixes cuda for #474
- LJFunctorCudaTest extended to also test LJFunctorCuda (no globals)
- Extended TraversalComparison to test LJFunctorCuda (no globals)

DummyParticles: Cuda fixes for #474

---

examples/sph/sph-main.cpp
src/autopas/molecularDynamics/LJFunctor.h
src/autopas/sph/SPHCalcDensityFunctor.h
src/autopas/sph/SPHCalcHydroForceFunctor.h
src/autopas/sph/SPHParticle.h
tests/testAutopas/tests/sph/SPHTest.cpp

Adapts SoAFunctor for #474 
- Part of #474 
- old tests still run through

DummyParticles: SPH: Adapts SoAFunctor for #474 

---

Jenkinsfile

Removes usage of old warnings plugin and replaces it with new warnings_NG plugin

Jenkins: Updates plugin usage

---

examples/md-flexible/CMakeLists.txt
examples/md-flexible/src/Generator.h
examples/md-flexible/src/parsing/MDFlexConfig.cpp
examples/md-flexible/src/parsing/YamlParser.cpp
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/pairwiseFunctors/CellFunctor.h

Some small stuff I stumbled upon...

Minor fixes

---

src/autopas/selectors/Configuration.h
src/autopas/selectors/tuningStrategy/PredictiveTuning.h
tests/testAutopas/tests/selectors/tuningStrategy/PredictiveTuningTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/PredictiveTuningTest.h

Removes most of the code duplications of the PredictiveTuningTest
- #511

code deduplication of PredictiveTuningTest

---

examples/md-flexible/input/fallingDrop.yaml
examples/md-flexible/src/Simulation.h
tools/autopasTools/generators/ClosestPackingGenerator.h
tools/autopasTools/generators/GridGenerator.h

Fixes about particle IDs
Cool video with trace lines that only work when the particle IDs work correctly.

Particle id fixes

---

README.md
examples/md-flexible/src/Simulation.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/iterators/ParticleIteratorInterface.h
src/autopas/utils/ExceptionHandler.h

Updates to readme

---

.lgtm.yml
Jenkinsfile
examples/md-flexible/tests/CMakeLists.txt
tests/CMakeLists.txt
tests/testAutopas/tests/containers/AllContainersTests.cpp
tests/testAutopas/tests/containers/AllContainersTests.h

- disables building of tests for lgtm.
- removes a few configurations from jenkinsfile
- minor @file fixes

disable building of tests for lgtm

---

src/autopas/AutoPas.h
src/autopas/selectors/tuningStrategy/BayesianClusterSearch.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianCluster.h
src/autopas/selectors/tuningStrategy/PredictiveTuning.h
src/autopas/selectors/tuningStrategy/TuningStrategyFactory.cpp
src/autopas/selectors/tuningStrategy/TuningStrategyFactory.h
src/autopas/utils/logging/PredictionLogger.cpp
tests/testAutopas/tests/selectors/tuningStrategy/BayesianClusterSearchTest.cpp

fix application of suffix in cluster and prediction logger

---

src/autopas/molecularDynamics/MoleculeLJ.h
src/autopas/particles/ParticleBase.h
src/autopas/sph/SPHParticle.h
tests/testAutopas/testingHelpers/NonConstructibleParticle.h
tests/testAutopas/testingHelpers/TouchableParticle.h

remove unnecessary cast

---

tests/testAutopas/tests/utils/MemoryProfilerTest.cpp
tests/testAutopas/tests/utils/MemoryProfilerTest.h

Add a basic functionality test for the MemoryProfiler

Memory Profiler Test

---

.github/workflows/doxygen-md-flexible.yml
.github/workflows/doxygen.yml
Jenkinsfile

Testing out gh actions

---

.github/workflows/doxygen-md-flexible.yml
.github/workflows/doxygen.yml
Jenkinsfile
cmake/modules/doxygen.cmake

Locally. I also tested Versions `1.9.0`, `1.9.1` but they give me warnings from our `Math.h`.

Doxygen Github Actions Rework

---

src/autopas/utils/ExceptionHandler.cpp
src/autopas/utils/ExceptionHandler.h

static inline instead of definition in .cpp

adds three static `inline`s.

---

.github/workflows/doxygen-md-flexible.yml
.github/workflows/doxygen.yml

Publishing is currently not working - here comes a fix

Fix doxygen publish

---

Jenkinsfile
cmake/modules/CodeCoverage.cmake
examples/sph-mpi/CMakeLists.txt
src/autopas/utils/Math.h

The upgrade of the dockerfiles to ubuntu 20 broke some stuff (of course....)

Fix CI Fails

---

src/autopas/options/ContainerOption.h

Discourage VCL because they are not optimal yet.

Discourage VCL

---

src/autopas/AutoPasDecl.h
src/autopas/AutoPasImpl.h
src/autopas/LogicHandler.h

Expose deleteParticle(Particle &)

---

src/autopas/containers/CompatibleLoadEstimators.h
src/autopas/utils/AutoPasConfigurationCommunicator.cpp

Bunch of small fixes for compiler or clang-tidy warnings.

Fix compiler warnings

---

src/autopas/molecularDynamics/autopasmd.h

Exclude functors that don't make sense from convenience file
- forked from #709

Less default includes

---

examples/md-flexible/src/TimeDiscretization.cpp
src/autopas/particles/ParticleBase.h
tests/testAutopas/tests/particles/MyMoleculeTest.cpp
tests/testAutopas/tests/particles/myMoleculeTest.cpp

Add new functions that check if moving a particle is within safe bounds.

Safer Particle Movement

---

src/autopas/tuning/AutoTuner.cpp
src/autopas/tuning/AutoTuner.h
tests/testAutopas/tests/tuning/AutoTunerTest.cpp

Weighting was done wrong if more than one rebuild happens during sampling. This PR fixes this.
- introduced in #669

Fix Calculation of weighted Sampling Average

---

src/autopas/utils/SimilarityFunctions.h

Fix type of loop var to resolve clang warning

Fix Compiler Warning
