Jenkinsfile

This should fix #13. The job was moved to a multi-branch project, so we now have the opportunity to store the pipeline directly in the source tree. There are various advantages to this approach, because it allows us to use some smart new features.
I also removed the e-mail notification that went out to the core development team on every build to reduce the verbosity. I would propose to replace that with either email that is only sent to the last committer. Another option would be to have Jenkins simply post a comment on the commit/Pull-Request, that way every user can specify whether they want to receive an e-mail in their GitHub settings.
The latter option could be a good idea either way, because we could also display useful additional information like test coverage in a comment.

Added Jenkinsfile, fix 13

---

src/utils/ExceptionHandler.cpp
src/utils/ExceptionHandler.h
tests/testAutopas/ExceptionHandlerTest.cpp
tests/testAutopas/ExceptionHandlerTest.h

we assume that ExceptionHandler::_behavior is set to throw throughout the explanations of this PR.
adds tests to properly check for the thrown error/exception when using the ExceptionHandler
if behavior is set to throw:
* fixes: throwing exceptions always produced a std::exception with meaningless what() methods
* feature: throwing a caught exception using the ExceptionHandler looses the type of the exception
e.g.
```C++
try{
// sth. that produces an error
} catch (std::exception& e){
ExceptionHandler::exception(e);  // produced wrong result
}
```
calling `ExceptionHandler::rethrow();` inside a catch block will now rethrow the caught exception. You can still reuse the normal `exception()` method, to provide additional information.
```C++
try{
// sth. that produces an error
} catch …
```

corrects exception throwing of ExceptionHandler

---

src/containers/DirectSum.h
src/containers/LinkedCells.h
src/pairwiseFunctors/CellFunctor.h
src/pairwiseFunctors/Functor.h
src/pairwiseFunctors/LJFunctor.h
tests/testAutopas/AoSvsSoATest.cpp
tests/testAutopas/mocks/MockFunctor.h

Referencing #42 
This removes the `SoALoad/Extract` calls from the cell functor since it called `Load/Extract` for each pairwise interaction. The `Load/Extract` is now done in separate iterations in the `iteratePairwiseSoA` methods of the containers.
Speed improvement on a grid example:
Container | Iterations | \#Particles | grid spacing | cutoff | 
--------------|--------------|--------------|---------------|-----------
Linked-Cells | 10 | 60^3 | 1 | 2.5 | 
Time for one iteratePairwise call in s:
Traversal | Old | New | Speedup
-------------|------|--------|--------------
c08 | .96 | .84 | 1.14
sli | .93 | .82 | 1.13

Fewer SoALoad/Extract calls

---

CMakeLists.txt
Jenkinsfile
examples/CMakeLists.txt
examples/basic/CMakeLists.txt
examples/md-flexible/CMakeLists.txt
examples/md/CMakeLists.txt
examples/sph-mpi/CMakeLists.txt
examples/sph-mpi/sph-main-mpi.cpp
examples/sph-verlet/CMakeLists.txt
examples/sph/CMakeLists.txt
examples/sphDiagramGeneration/CMakeLists.txt
tests/testAutopas/CMakeLists.txt

fixes #54 
* `make checkExamples` or `ninja checkExamples` will check the examples. The checks are disabled for the normal `make test` (`ninja test`) or `ctest`.
* adds the check to jenkins using the release target. (everything else is too time-costly)
* the checks use ctest's addTest() feature.
To add new tests just copy one of the other tests.
build failing because of #53

Check Examples

---

src/containers/VerletListHelpers.h
src/containers/VerletLists.h
src/utils/ExceptionHandler.h
src/utils/SoA.h
tests/testAutopas/ExceptionHandlerTest.cpp

the verlet-lists are now (re)build using SoA's.
This saves a lot of lookups (hash generations) and some other things.
Speedup is clearly visible, especially as soon as there are more than one particle per cell:
Verlet Lists (md-main, 1000 cells):
type | particle count | rebuild time before | rebuild time now | kernel time (LJ)
------ | ----------------- | ------------------------ | ---------------------- | -----------------
soa | 10.000 | 0.12 | 0.07 | 0.010
aos | 10.000 | 0.10 | 0.05 | 0.018
soa | 1.000 | 1.8e-3 | 1.4e-3 | 1.9e-4
aos | 1.000 | 1.6e-3 | 1.2e-3 | 1.8e-4
Linked Cells (md-main, 1000 cells):
type | particle count | kernel time (LJ)
------ | --------------- | ----
soa | 10.000 | 0.032
aos | 10.000 | 0.07
soa | 1.000 | 6.8e-4
aos | 1.000 | 1.0e-3
meaning, that in this case …

verlet list rebuild optimizations

---

examples/md/measurePerf.sh
src/iterators/SingleCellIterator.h
src/iterators/SingleCellIteratorInterface.h
src/iterators/SingleCellIteratorWrapper.h
src/pairwiseFunctors/CellFunctor.h

Problem:
ParticleIteratorWrappers were decreasing performance of AoS functors.
See these plots (orange and blue solid lines):
notes:
* (without the linked-cells soa version, as this is sort of totally different and the previous performance was very bad)
* verlet lists: for very few particles (less than 0.1 particles per cell), they are slower than before. not entirely sure why this happens.
* linked cells: slower than before up to 0.5 particles per cell. this most likely stems from the overhead of the wrappers, i.e. having additional `new` calls, etc.. This is probably also the reason for the decreased performance of the verlet lists.
* some of the speedup comes from new return statements inside the CellFunctors.
@FG-TUM In theory we can remove the wrapper for the SingleCellIterators, as …

AoS performance improvements

---

tests/testAutopas/DirectSumTest.cpp
tests/testAutopas/DirectSumTest.h
tests/testAutopas/LinkedCellsTest.cpp
tests/testAutopas/LinkedCellsTest.h
tests/testAutopas/VerletListsTest.cpp
tests/testAutopas/VerletListsTest.h

what the title says.
Resolving #77 
Tests need to be individual for each container since this behavior can be container specific.

IsContainerUpdate needed tests

---

src/autopas/cells/FullParticleCell.h
src/autopas/containers/CellBlock3D.h
src/autopas/containers/LinkedCells.h
src/autopas/utils/WrapOpenMP.h
tests/testAutopas/LinkedCellsTest.cpp

Faster and more parallel implementation of `LinkedCells::updateContainer()`
Tested on my machine (i7-7700 8x3.6GHz)
- 1,000,000 Particles (uniform random distribution)
- 52x 52 x 52 Cells
- random = particle jumps to a complete random location in the domain
- realistic = particle jumps to a random neighbor cell
- omitting locks (= allowing data races) has no significant impact
Particle relocations [ms] |  no | random 50%  | random 100% | realistic 5% | realistic 10%
------------ | ------------- | ------------- | ------------- | ------------- | -------------
old                         | 180 | 285 | 285 | 185 | 190
lock everything      |   30 | 240 | 250 |   42 | 50
add-barrier-delete |   35 | 250 | 288 |   47 | 58
Versions can be compared in 2330c573c0dde6b5da3b1a1eec670edf915ccf0f

Faster update container

---

examples/sph-mpi/sph-main-mpi.cpp
examples/sph/sph-main.cpp
src/autopas/containers/CellBlock3D.h
src/autopas/containers/CellBorderAndFlagManager.h
src/autopas/containers/DirectSum.h
src/autopas/containers/LinkedCells.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/VerletLists.h
src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
src/autopas/containers/cellPairTraversals/C08Traversal.h
src/autopas/containers/cellPairTraversals/SlicedTraversal.h
src/autopas/iterators/ParticleIterator.h
src/autopas/iterators/RegionParticleIterator.h
src/autopas/particles/Particle.h
src/autopas/utils/ThreeDimensionalMapping.h
src/autopas/utils/inBox.h
tests/testAutopas/InBoxTest.cpp
tests/testAutopas/RegionParticleIteratorTest.cpp
tests/testAutopas/RegionParticleIteratorTest.h
tests/testAutopas/testingHelpers/GaussianGenerator.h
tests/testAutopas/testingHelpers/RandomGenerator.h

The region iterator now...
This PR aims to close #2 
Tests:
- Domain 10x10x10 + Halo (size: 0.2)
- Cutoff / cell length: 0.2
- Number of cells: 140608 (52x52x52)
- 1 million particles uniformly randomly distributed.
- Time in ms
- T = Number of threads
Description | Region    | Old (T=1) | New (T=1) | Old (T=8) | New (T=8) | Comment
------------ | ------------ | ------------ | ------------ | ------------ | ------------ | ------------ 
~6.4% of domain | [5 5 5] to [9 9 9]                     | 31 | 3 | 10 | 2 |probably realistic case
Full domain | [-0.2 -0.2 -0.2] to [10.2 10.2 10.2]  | 37 | 45 | 9 | 13 | Here the normal iterator should be used wich needs ~18 ms (T=1)
Full domain w/o halo | [0 0 0] to [10 10 10]         | 39 | 46 | 9 | 12 | Here the normal iterator should be used wich …

Faster region iterators

---

Jenkinsfile

build errors were not correctly shown.
also shows warnings correctly now.
**the error:**
redirecting using
```
cmd &> file
``` 
is not supported in the normal shell.
**fix:**
used
```
cmd > file 2>&1
```
instead
fixes #107

show build errors correctly

---

cmake/modules/other-compileroptions.cmake
src/autopas/sph/SPHCalcDensityFunctor.h

closes #110 
**The Bug**
sph functions weren't properly vectorized anymore
**The possibilities**
either enable `-ffast-math`
or
enable `-fno-math-errno`
**The fix**
The latter seemed the better alternative, so I enabled for all configurations. `-fno-math-errno` also exists for all tested compilers (i.e. clang, gnu, intel)

fix sph vectorization

---

src/autopas/containers/CellBorderAndFlagManager.h
src/autopas/iterators/ParticleIteratorWrapper.h
src/autopas/iterators/RegionParticleIterator.h
tests/testAutopas/RegionParticleIteratorTest.cpp

Makes the Tests for the RegionParticleIterator use OpenMP.
Discovered and fixed one bug (See below)
- #PR

RegionParticleIterator tests now openmp + bugfix

---

src/autopas/selectors/AutoTuner.h
src/autopas/selectors/ContainerSelector.h
src/autopas/selectors/TraversalSelector.h
src/autopas/utils/TrivialHash.h
tests/testAutopas/TraversalSelectorTest.cpp
tests/testAutopas/TraversalSelectorTest.h

Introducing swappable strategies for the tuner classes.

Selector strategies

---

src/autopas/containers/cellPairTraversals/SlicedTraversal.h
tests/testAutopas/C08TraversalTest.h
tests/testAutopas/SlicedTraversalTest.cpp
tests/testAutopas/SlicedTraversalTest.h

Smarter sliced

---

src/autopas/iterators/RegionParticleIterator.h
tests/testAutopas/RegionParticleIteratorTest.cpp
tests/testAutopas/RegionParticleIteratorTest.h

Fixes RegionParticleIterators pointing to wrong cells, when iterating over halo or own cells using IteratorBehavior::haloOnly or IteratorBehavior::ownedOnly.

fixes RegionParticleIterator when using a non-default IteratorBehavior

---

src/autopas/cells/FullParticleCell.h
src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
src/autopas/utils/WrapOpenMP.h

Replaces autopas_lock_t (wrapper for omp_lock_t if AutoPas is compiled with OpenMP // to some dummy lock if AutoPas is compiled without OpenMP) with a proper lock class.
This makes copying of objects that have a lock straightforward and is no longer a possible problem.

Make autopas use a proper lock class

---

src/autopas/AutoPas.h
src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
tests/testAutopas/tests/autopasInterface/AutoPasTest.cpp

Allows for AutoPas to somehow cope with changing MPI domains.
Two strategies are supported and tested:
1.  
```
0. create normal AutoPas container + initialize and fill with particles
1. create additional AutoPas container + initialize
2. fill additional AutoPas container with particles
3. std::move the new container over the old one.
```
```C++
// 0. normal container
autopas::AutoPas<autopas::Particle, autopas::FullParticleCell<autopas::Particle>> autoPas;
autoPas.init({0., 0., 0.}, {10., 10., 10.}, 1., 0, 1, {autopas::ContainerOptions::linkedCells},
{autopas::TraversalOptions::c08});
// 1. create new AutoPas container + initialize
decltype(autoPas) autoPasTmp;
autoPasTmp.init({0., 0., 0.}, {5., 5., 5.}, 1., 0, 1, {autopas::ContainerOptions::linkedCells}, …
```

Enable and test rebuilding of AutoPas

---

src/autopas/containers/CellBlock3D.h
tests/testAutopas/tests/containers/CellBlock3DTest.cpp
tests/testAutopas/tests/containers/CellBlock3DTest.h

Particles that were added within the domain, but very close to the boundary were sometimes added to HaloCells. This has been fixed.

Fixes CellBlock3D wrongly assigning cell to some particles

---

src/autopas/AutoPas.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
tests/testAutopas/tests/autopasInterface/AutoPasTest.cpp

Adds interfaces to make verlet lists usable in the external AutoPas interface
Implements the following functions:
Tested:
- dependency for: https://github.com/ls1mardyn/ls1-mardyn/pull/54

verlet list AutoPas interface usability changes

---

src/autopas/AutoPas.h
src/autopas/selectors/AutoTuner.h
tests/testAutopas/tests/autopasInterface/AutoPasTest.cpp

- #165 
- https://github.com/ls1mardyn/ls1-mardyn/pull/54

add function needsContainerUpdate to autopas interface

---

Jenkinsfile

Replaces the deprecated warnings jenkins plugin with warnings-ng.
- #147
- Built on jenkins

Migrate jenkins pipeline to warnings-ng, resolves #147

---

examples/md-flexible/MDFlexParser.cpp
examples/md-flexible/measurePerf.sh

Fixes bugs in measureperf.sh of md-flexible

fix md-flexible's measureperf.sh

---

src/autopas/pairwiseFunctors/Functor.h
src/autopas/pairwiseFunctors/LJFunctor.h
src/autopas/pairwiseFunctors/LJFunctorAVX.h
src/autopas/selectors/AutoTuner.h
tests/testAutopas/tests/pairwiseFunctors/LJFunctorTest.cpp

Adds initTraversal and endTraversal to functors.
These will be called by AutoPas at the start, resp. the end of a simulation to implement things like global value accumulation.
They were needed, as the newton3 type of a simulation cannot be known anymore from the outside
- needed since #170 that newton3 switching by autopas

Adds initTraversal and endTraversal

---

Jenkinsfile
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/particles/Particle.h
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp
tests/testAutopas/tests/selectors/ContainerSelectorTest.h

This PR introduces tests and fixes for the conversion between containers
- ref #155

Test and Fix Container Conversion

---

src/autopas/containers/CellBlock3D.h
src/autopas/containers/CellBorderAndFlagManager.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/iterators/ParticleIterator.h
src/autopas/iterators/RegionParticleIterator.h
src/autopas/particles/Particle.h
tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.h
tests/testAutopas/tests/containers/directSum/DirectSumContainerTest.cpp
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp

Implements parts of #215:
- #215

Adapt owed particle bahavior [ad PR #215]

---

src/autopas/AutoPas.h

print an error if static type of given functor in AutoPas::iteratePairwise() is autopas::Functor.

Error message if wrong functor type is given in AutoPas::iteratePairwise

---

examples/sphDiagramGeneration/sph-diagram-generation.cpp
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/TraversalSelector.h
src/autopas/selectors/TraversalSelectorInfo.h
tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
tests/testAutopas/tests/selectors/TraversalSelectorTest.cpp

Refactored TraversalSelector: Extracted TraversalSelectorInfo, which represents the container specific data, and made generateTraversal() method static.
Before, all containers included TraversalSelector which itself included all of the traversals. Now, these dependencies are reduced to the necessary ones.
This refactoring was probably the simplest one as other ideas would have been problematic because of the template parameters of generateTraversal().
With all the tests from before.

Refactored TraversalSelector to remove a lot of unnecessary dependencies

---

tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp

1. There were multiple `EXPECT_CALL` statements with the same signature. GMock only uses the last one of these [(documented here)](https://github.com/google/googletest/blob/master/googlemock/docs/ForDummies.md#using-multiple-expectations), leading to unrecognized expectations.
2. The wrong counter for "without newton3" was used (`callsNewton3Pair` instead of `callsNonNewton3Pair`) (old line 194, new line 190)
3. Call counters were not atomic and caused data races. Changed type to std::atomic.

Bug fixes Newton3OnOffTest

---

src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
src/autopas/containers/cellPairTraversals/CBasedTraversal.h

Move initTraversal/endTraversal to superclass CBasedTraversal, thus remove a lot of code duplicates.

Refactoring: Move initTraversal/endTraversal to superclass CBasedTraversal

---

cmake/modules/CodeCoverage.cmake

Correct wrong formatted CMake comments.
I didn't turn comment formatting off, since it is beneficial most of the time. If comments include some sort of code or ascii art which shouldn't be formatted, code formatting for comments can be turned off using the following syntax
```
```

Correct wrong formatted CMake comments

---

examples/cluster-test/cluster-test.cpp
examples/sph-mpi/sph-main-mpi.cpp
examples/sph-traversals/sph-traversals.cpp
examples/sph-verlet/sph-main-verlet.cpp
examples/sph/sph-main.cpp
examples/sphDiagramGeneration/sph-diagram-generation.cpp
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
src/autopas/selectors/AutoTuner.h
tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
tests/testAutopas/tests/containers/LinkedCellsVersusVerletClusterListsTest.cpp
tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.cpp
tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.cpp
tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp
tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp
tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp
tests/testAutopas/tests/sph/SPHTest.cpp

Removed newton 3 parameter from all iteratePairwise methods in the containers.
None
None
Jenkins

Removed newton3 parameter from all iteratePairwise methods in the containers

---

.github/CONTRIBUTING.md
CMakeLists.txt
Jenkinsfile
README.md

Enables c++17 for host code compilation.
Cuda compilation is performed using c++14
- #194 
- #189 

enable c++17

---

tests/testAutopas/tests/containers/linkedCells/traversals/SlicedTraversalTest.cpp
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp

NumThreadGuard was always used without a name, so they were destroyed immediately, without guarding anything.
This is now fixed.

fix thread guards

---

examples/sphDiagramGeneration/sph-diagram-generation.cpp
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/selectors/TraversalSelector.h
src/autopas/selectors/TraversalSelectorInfo.h
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
tests/testAutopas/tests/selectors/TraversalSelectorTest.cpp

Removes the unnecessary ParticleCell template from TraversalSelectorInfo

remove ParticleCell template from TraversalSelectorInfo

---

src/autopas/AutoPas.h
src/autopas/LogicHandler.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/utils/AlignedAllocator.h
src/autopas/utils/AutoPasMacros.h
src/autopas/utils/SoA.h
tests/testAutopas/mocks/MockVerletLists.h

Implements some c++17 changes, to make the code more readable or work better.
- cannot use std::hardware_destructive_interference_size, as this can only be found in the microsoft library, see: P0154R1 in https://en.cppreference.com/w/cpp/compiler_support#cpp17

c++17 cleanup

---

README.md
src/autopas/pairwiseFunctors/LJFunctor.h

adds ignore to SoAFunctor() for the thread sanitizer to block a data race currently detected in C01Traversal using the combined mechanism, see #285
- blocks data race from #285

ignore data race from #285

---

.lgtm.yml

Mark the `libs` directory as library in `.lgtm.yml` to tell lgtm not to spawn errors found in the libraries.

mark libs as library in lgtm

---

src/autopas/containers/linkedCells/traversals/C01Traversal.h
src/autopas/containers/linkedCells/traversals/C18Traversal.h
src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
src/autopas/pairwiseFunctors/FlopCounterFunctor.h
src/autopas/pairwiseFunctors/Functor.h
src/autopas/pairwiseFunctors/LJFunctor.h
src/autopas/pairwiseFunctors/LJFunctorAVX.h
src/autopas/particles/ParticleBase.h
src/autopas/sph/SPHCalcDensityFunctor.h
src/autopas/sph/SPHCalcHydroForceFunctor.h
src/autopas/sph/SPHParticle.h
src/autopas/utils/SoA.h
tests/testAutopas/mocks/MockFunctor.h
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.h
tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.h

Functors now explicitly declare which values are computed and which values are needed. 
- #274 (base branch)

Functor refactoring

---

examples/sph-mpi/sph-main-mpi.cpp
examples/sph/sph-main.cpp
src/autopas/AutoPas.h
src/autopas/LogicHandler.h
tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp

introduces bool that specifies whether the container within autopas was rebuild on updateContainer. This bool is returned together with the vector of invalid particles as a pair on a call to AutoPas::updateContainer()
Needed for a couple of different reasons. 
- performance: the possibility to neglect a leaving particle exchange
- correctness: it is now clear to the outside caller what the state of autopas is.

make updateContainer also return whether the container was updated

---

cmake/modules/other-compileroptions.cmake
examples/sph/sph-main.cpp
src/autopas/containers/linkedCells/traversals/C01Traversal.h
src/autopas/containers/linkedCells/traversals/C04Traversal.h
src/autopas/containers/linkedCells/traversals/C18Traversal.h
src/autopas/utils/ArrayMath.h
src/autopas/utils/ArrayUtils.h
src/autopas/utils/NumberSet.h
tests/testAutopas/tests/containers/CellBlock3DTest.cpp
tests/testAutopas/tests/iterators/RegionParticleIteratorTest.cpp
tests/testAutopas/tests/utils/ArrayMathTest.cpp
tests/testAutopas/tests/utils/ArrayUtilsTest.cpp
tests/testAutopas/tests/utils/NumberSetTest.cpp

This PR adds a generic `to_string` function to `ArrayMath`, which can convert all containers (`cbegin` + `cend` are required) to a string representation (really helpful for debugging). 
It also fixes a bug in `NumberSet`. If the set was empty, the string conversion method never terminated.

Add generic to_string function, Bug fix NumberSet

---

src/autopas/containers/CellBlock3D.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
tests/testAutopas/tests/autopasInterface/IteratorTest.cpp
tests/testAutopas/tests/autopasInterface/IteratorTest.h

The cells the RegionParticleIterator iterates through are now always selected using a by the skin increased search region. This is needed for the verlet like interface.

makes RegionParticleIterators use increased search Regions when using LinkedCells

---

src/autopas/containers/CellBlock3D.h

getNearbyHaloCells will now always return the most likely cell, i.e., the cell directly related to the particle position first.
This function is used within updateHaloParticle of the Linked-Cells algorithm. Thus having the most likely cell first saves a large amount of instructions (see below).
Profiling using ls1-mardyn
without optimization: 24B instructions in this function
with optimization: 3.3B instructions in this function

optimize getNearbyHaloCells function in CellBlock3D 

---

src/autopas/pairwiseFunctors/LJFunctorAVX.h

In the SoAKernel if all four force calculations are masked away skip the calculation.

AVX Functor shortcut

---

.github/CONTRIBUTING.md
Jenkinsfile
src/autopas/cells/FullParticleCell.h
src/autopas/cells/RMMParticleCell2T.h
src/autopas/containers/verletListsCellBased/verletLists/neighborLists/asBuild/AsBuildPairGeneratorFunctor.h
src/autopas/pairwiseFunctors/Functor.h
src/autopas/utils/SoA.h
src/autopas/utils/WrapOpenMP.h
tests/testAutopas/testingHelpers/NumThreadGuard.h

This PR removes all occurrences of `NULL` and `assert` in `.h` and `.cpp` files. Custom checks were added to Jenkins prevent insertion of those constructs. In addition, all custom checks were extended to also cover `tests` and `examples`. Contribution guidelines were updated accordingly.

Remove NULL and assert

---

examples/md-flexible/Simulation.h

After reading this horrible document ( https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf ) I added some more data to the ASCII VTK output.
There still needs to be a command line option for the vtk write frequency (comes with #337 afaik)
- merges in #270

More Data in VTK Files

---

.github/CONTRIBUTING.md
examples/benchmark-cuda/main.cpp
examples/sph-traversals/sph-traversals.cpp
examples/sphDiagramGeneration/sph-diagram-generation.cpp
src/autopas/containers/ParticleContainer.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/containers/verletListsCellBased/verletLists/neighborLists/VerletNeighborListInterface.h
src/autopas/containers/verletListsCellBased/verletLists/neighborLists/asBuild/VerletNeighborListAsBuild.h
src/autopas/containers/verletListsCellBased/verletLists/traversals/TraversalVerlet.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/ContainerSelector.h
tests/testAutopas/tests/containers/CudaTraversalVersusDirectSumTest.cpp
tests/testAutopas/tests/containers/CudaTraversalVersusDirectSumTest.h
tests/testAutopas/tests/containers/LinkedCellsVersusDirectSumTest.h
tests/testAutopas/tests/containers/LinkedCellsVersusVarVerletListsTest.h
tests/testAutopas/tests/containers/LinkedCellsVersusVerletClusterListsTest.h
tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsCellsTest.h
tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.h
tests/testAutopas/tests/containers/directSum/DirectSumContainerTest.cpp
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.h
tests/testAutopas/tests/iterators/ParticleIteratorTest.cpp
tests/testAutopas/tests/iterators/RegionParticleIteratorTest.cpp
tests/testAutopas/tests/iterators/RegionParticleIteratorTest.h
tests/testAutopas/tests/sph/SPHTest.cpp

Remove redundant "Particle" template parameter from all container classes.
- #323 (not completely resolved)

Remove "Particle" template parameter

---

src/autopas/AutoPas.h
src/autopas/iterators/ParticleIteratorWrapper.h

This PR adds type aliases for the iterator types.
This prevents internal changes inside of AutoPas to propagate to the outside and thus provides a more stable interface.
- #350 changes like these.

Provide type aliases for the iterator types

---

src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
src/autopas/containers/cellPairTraversals/CBasedTraversal.h
src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h
src/autopas/containers/linkedCells/traversals/C08CellHandler.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C18TraversalVerlet.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/SlicedTraversalVerlet.h
src/autopas/pairwiseFunctors/CellFunctor.h
tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp

- Fixes inappropriate sorting directions being used in some cases. (mainly DirectSum, but possibly also verlet lists)
- Fixes VerletListsCellsTraversal not iterating over verlet lists of some halo cells (#355)

Fix calculation of DirectSum (wrong sorting) and VerletListsCells (interactions with halo particle were skipped)

---

src/autopas/selectors/AutoTuner.h

reducedValue from OptimumSelector::optimumValue() was not used properly, instead the tuningstrategies were always only using the last measured time.

fix all tuning-strategies using the last measured time

---

src/autopas/containers/verletClusterLists/VerletClusterCellsParticleIterator.h
src/autopas/iterators/ParticleIterator.h
src/autopas/selectors/FeatureVector.h
tests/testAutopas/tests/selectors/tuningStrategy/BayesianSearchTest.cpp

Changes the return type of the - operator of FeatureVector to Eigen::VectorXd. This seems reasonable since the previously returned feature vector was only used to be cast to a Eigen::VectorXd. Also with #348 the construction of invalid options will not be possible anymore.
- #348

Bayesian Search: Change FeatureVector diff

---

src/autopas/containers/linkedCells/traversals/C04SoATraversal.h

Disable the C04SoATraversal for cell size factors < 1.
This should be reverted as soon as https://github.com/AutoPas/AutoPas/issues/354 is fixed.
- fix in progress: #364 
- not resolved but suppresses: #354

Disable the C04SoATraversal for cell size factors < 1.

---

Jenkinsfile
cmake/modules/cuda.cmake
cmake/modules/other-compileroptions.cmake
tests/testAutopas/tests/pairwiseFunctors/LJFunctorCudaTest.cpp

Make clang compiler work with nvcc, 
* by adding missing
```
$<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=>
```
* and by passing the host compiler to nvcc via -ccbin
- There exist compatibility restrictions between nvcc and clang! nvcc 10.1 is not compatible with clang >=9.

Fix nvcc + clang not compiling

---

cmake/modules/clang-format.cmake
cmake/modules/cmake-format.cmake
examples/sph-mpi/CMakeLists.txt

Removes lots of list operations in clang-format.cmake and cmake-format.cmake.
Previously also files in build directories were traversed and later on removed, this is now fixed.
Exemplary timing results for the cmake command (with 15 build directories):
old      | new
-------- | -------
85.7 s | 3.5 s

Performance improvements for cmake files

---

src/autopas/containers/ParticleContainer.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/ContainerSelector.h

Changes VerletListsLinkedBase,s.t., it inherits directly from ParticleContainerInterface instead of ParticleContainer.
The methods provided in ParticleContainer and especially the cells are not needed and sometimes produce completely wrong results if not overwritten.
This prevents stupid errors.

Make VerletListsLinkedBase directly inherit from ParticleContainerInterface

---

examples/md-flexible/parsing/MDFlexConfig.cpp
examples/md-flexible/parsing/YamlParser.cpp

When defining new particle types through a yaml file defaults need to be cleared.

Fix particle properties init

---

src/autopas/AutoPas.h
src/autopas/LogicHandler.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/verletClusterLists/VerletClusterCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h

AutoPas Interface:
- addParticle(Particle&) is now addParticle(const Particle&)
- addOrUpdateHaloParticle(Particle&) is now addOrUpdateHaloParticle(const Particle&)
Container Interface:
- addParticle(Particle&) is now addParticle(const Particle&)
- addHaloParticle(Particle&) is now addHaloParticle(const Particle&)
- updateHaloParticle(Particle&) is now updateHaloParticle(const Particle&)

Make all methods adding or updating particles take const Particle&

---

Jenkinsfile
src/autopas/AutoPas.h

Jenkins is currently not aborting when doxygen fails.
This PR fixes this by adding a post section to the doxygen step:
```
post {
failure {
echo "failure"
error "warnings in doxygen documentation"
}
}
```

Fixes Jenkins not aborting when doxygen fails

---

.github/CONTRIBUTING.md

Updates the clang-format version from 6.0 to 9 in CONTRIBUTING.md.

Update clang-format version in CONTRIBUTING.md

---

cmake/modules/other-compileroptions.cmake
src/autopas/AutoPas.h
src/autopas/CMakeLists.txt
src/autopas/selectors/FeatureVector.h
src/autopas/selectors/tuningStrategy/BayesianSearch.h
src/autopas/selectors/tuningStrategy/GaussianProcess.cpp
src/autopas/selectors/tuningStrategy/GaussianProcess.h
src/autopas/selectors/tuningStrategy/TuningStrategyFactory.cpp
src/autopas/selectors/tuningStrategy/TuningStrategyFactory.h
tests/testAutopas/CMakeLists.txt
tests/testAutopas/tests/selectors/tuningStrategy/GaussianProcessTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianProcessTest.h

This PR introduces TuningStrategyFactory.
This mainly removes public dependencies by removing their inclusion through AutoPas.h.
Instead, they now are them only included within TuningStrategyFactory.cpp.
The following dependencies are removed:
* ActiveHarmony
* Eigen3

Introduces TuningStrategyFactory

---

CMakeLists.txt
cmake/modules/cuda.cmake
cmake/modules/other-compileroptions.cmake

uses target_compile_features to set cxx_std_17 and cuda_std_14.
This affects cmake >= 3.17.

Uses target_compile_features to set cxx_std_17 and cuda_std_14

---

src/autopas/selectors/tuningStrategy/BayesianSearch.h
src/autopas/selectors/tuningStrategy/FullSearch.h
src/autopas/utils/NumberSet.h
src/autopas/utils/NumberSetFinite.h

I was wondering, why the TuningsStrategyFactory was always rebuilt, this fixes that.

Remove unneeded includes from Bayesian and FullSearch

---

src/autopas/containers/ParticleDeletedObserver.h
src/autopas/containers/verletClusterCells/VerletClusterCells.h
src/autopas/containers/verletClusterCells/VerletClusterCellsParticleIterator.h
src/autopas/containers/verletClusterLists/ClusterTower.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
tests/testAutopas/tests/autopasInterface/IteratorTest.cpp

Implements the test requested in #435.
As expected, this test fails for VerletClusterCells.
- Depends on #430 

Fix deletion using RegionParticleIterators for VerletClusterCells

---

src/autopas/utils/StaticSelectors.h

The StaticSelectors.h class had one wrong path to VerletCell and one DirectSum was given two templates but takes only one. 
- none
- none

fix errors in StaticSelectors.h

---

examples/md-flexible/Simulation.h
examples/md-flexible/parsing/CLIParser.cpp
examples/md-flexible/parsing/CLIParser.h
examples/md-flexible/parsing/MDFlexConfig.cpp
examples/md-flexible/parsing/MDFlexConfig.h
examples/md-flexible/parsing/MDFlexParser.cpp
examples/md-flexible/parsing/MDFlexParser.h
examples/md-flexible/parsing/YamlParser.cpp
examples/md-flexible/parsing/YamlParser.h
src/autopas/AutoPas.h
src/autopas/options/TuningStrategyOption.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/tuningStrategy/ActiveHarmony.h
src/autopas/selectors/tuningStrategy/BayesianSearch.h
src/autopas/selectors/tuningStrategy/FullSearch.h
src/autopas/selectors/tuningStrategy/GaussianProcess.cpp
src/autopas/selectors/tuningStrategy/GaussianProcess.h
src/autopas/selectors/tuningStrategy/PredictiveTuning.h
src/autopas/selectors/tuningStrategy/RandomSearch.h
src/autopas/selectors/tuningStrategy/SetSearchSpaceBasedTuningStrategy.h
src/autopas/selectors/tuningStrategy/TuningStrategyFactory.cpp
src/autopas/selectors/tuningStrategy/TuningStrategyFactory.h
src/autopas/selectors/tuningStrategy/TuningStrategyInterface.h
src/autopas/selectors/tuningStrategy/TuningStrategySuperClass.h
tests/testAutopas/tests/options/OptionTest.cpp
tests/testAutopas/tests/options/OptionTest.h
tests/testAutopas/tests/selectors/tuningStrategy/PredictiveTuningTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/PredictiveTuningTest.h

If the _currentConfig variable is in the super class instead of the separate tuning strategies, removeN3Option() can be in the super class, but then the super class can only be used for FullSearch and Predicitve Tuning, because right now the other classes use a different data type for _currentConfig.
I would choose the current implementation, but I wanted to mention the other possibility.
- none

SuperClass for tuning strategies and user input for PredicitveTuning

---

CMakeLists.txt
Jenkinsfile
cmake/modules/OpenMP.cmake
src/autopas/CMakeLists.txt

Update Jenkinsfile to use the new Archer image.
This archer image uses the new llvm-integrated archer version:
https://github.com/llvm/llvm-project/tree/master/openmp/tools/archer/
This update becomes needed, as the old version provided false errors in #453.
Archer is now fully integrated into the thread-sanitizer, so we more or less only use that now and can remove any Archer specific functions from the cmake files.

Update to use new archer image

---

examples/md-flexible/Simulation.h

Calculation fix for time and performance calculations in md-flexible
- None
- fixes time calculation from ns to s

Calculation fix for time and performance calculations in md-flexible

---

examples/md-flexible/src/Thermostat.h

Fix parallel Access to Random Engine in Thermostat

---

src/autopas/containers/CellBlock3D.h
src/autopas/containers/linkedCells/LinkedCells.h

Replaces out parameters in `CellBlock3D::getCellBoundingBox()` by returning a pair.

Fixes #473.

---

examples/sph/sph-main.cpp
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/tuningStrategy/ActiveHarmony.h
src/autopas/utils/Timer.h

This changes the INIT_RADIUS parameters of ActiveHarmony from 0.5 to 0.7.

Change INIT_RADIUS of ActiveHarmony to fix #500

---

src/autopas/selectors/tuningStrategy/ActiveHarmony.h

The in #500 described bug was caused by an implicit conversion from long to double. The invalidateConfiguration method thus reported good times to Active Harmony which in turn learned to return invalid configurations. So the only way for a valid configuration to be chosen would have been to have very short time steps or be lucky and not have to invalidate any configs.
* Since the bug described in #500 could not be observed universally, someone else should test this fix on their machine.

Fix issue #500

---

.github/CONTRIBUTING.md

The guide is based on the changes I made in commit 3af52a21118aee9bb2533e7358632cf256ce235d
I left out a lot of detailed changes, because they were specific to the option I implemented, but tried to at least include some pointers on where to start.

add guide to making options tunable

---

examples/md-flexible/src/Simulation.h
src/autopas/selectors/AutoTuner.h

Move tuning indication to AutoPas logger output so that it appears the same way everywhere AutoPas is used.

Indicate tuning

---

examples/md-flexible/input/testTuning/MDFlex_Case1.yaml
examples/md-flexible/input/testTuning/MDFlex_Case2.yaml
examples/md-flexible/scripts/extractClusterGraphCombine.py
examples/md-flexible/scripts/extractClusterGraphSeparate.py
src/autopas/selectors/FeatureVector.h
src/autopas/selectors/FeatureVectorEncoder.h
src/autopas/selectors/tuningStrategy/BayesianClusterSearch.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianCluster.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianClusterLogger.h
src/autopas/selectors/tuningStrategy/GaussianModel/GaussianModelTypes.h
src/autopas/utils/NumberInterval.h
src/autopas/utils/NumberSet.h
src/autopas/utils/NumberSetFinite.h
src/autopas/utils/Random.h
tests/testAutopas/tests/selectors/FeatureVectorTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/BayesianClusterSearchTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianClusterTest.cpp
tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianClusterTest.h

BayesianClusterSearch:
- Sample for each cluster in the first tuning phase
- Added iteration as a continuous dimension in order to reduce the consideration of evidence over time.

BayesianClusterSearch initial sampling + evidence decay

---

CMakeLists.txt
cmake/tests/has_avx_test.cpp
examples/md-flexible/CMakeLists.txt
src/autopas/molecularDynamics/LJFunctorAVX.h
tests/testAutopas/tests/molecularDynamics/LJFunctorAVXTest.cpp
tests/testAutopas/tests/molecularDynamics/LJFunctorAVXTest.h

Replaces unaligned loads and stores in LJFunctorAVX to be able to simulate with non-aligned SoAs from SoAViews (combined SoAs)
Should probably be implemented using a template parameter to decide whether aligned or unaligned intrinsics should be used.
- fixes md-flexible not being build if mpi is not present.
```bash
./md-flexible --no-end-config --no-flops --functor lennard-jones-AVX2 --deltaT 0 --particle-generator uniform --log-level debug --traversal lc_c04_combined_SoA --particles-total 71
```

unaligned loads and stores for LJFunctorAVX

---

src/autopas/AutoPas.h
src/autopas/CMakeLists.txt
src/autopas/Version.h.in
version.cmake

This code has more or less been copy-pasted from cmake's configuration.
* Adds git version to the version string.
* Adds `dirty` to version string, if the git tree is not clean
* Prints AutoPas_Version to info log. E.g.,
```
[2020-10-13 13:08:29.999] [AutoPasLog] [info] AutoPas Version: 0.1.0-cef07c3-dirty
```
Change of the version number will currently only be triggered if cmake is called. This could be changed 

Adds proper version info.

---

src/autopas/pairwiseFunctors/FlopCounterFunctor.h
src/autopas/utils/ArrayMath.h

The previous implementation of the dot product used `stl::inner_product`. Looking at the assembly output this turned out to be inefficient. The new implementation uses template parameter pack expansion for a compile-time unrolled explicit summation.

dot product: 

---

src/autopas/molecularDynamics/LJFunctor.h

If applyShift was false, the value of shift was undefined in SoAFunctorSingle.

Fixes shift6 in SoAFunctorSingle not being initialized.

---

src/autopas/AutoPas.h
src/autopas/InstanceCounter.h
src/autopas/containers/UnknowingCellBorderAndFlagManager.h
src/autopas/containers/cellPairTraversals/CBasedTraversal.h
src/autopas/containers/verletClusterCells/VerletClusterCells.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/varVerletLists/neighborLists/asBuild/VerletNeighborListAsBuild.h
src/autopas/iterators/ParticleIterator.h
src/autopas/iterators/RegionParticleIterator.h
tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.cpp
tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.h

- Removes static namespace members, as these have per definition internal linkage and are very bad.
Moves them to class members, which, by default, have external linkage.
- Removes static, thread-private members from VerletNeighborListAsBuild and the VerletClusterLists test.

Removes static namespace members

---

examples/md-flexible/src/Simulation.h
src/autopas/AutoPas.h

```
examples/md-flexible/md-flexible --no-end-config --no-flops --traversal vlc_c18 --particle-generator grid --cutoff 1 --particle-spacing 1.1 --particles-per-dimension 100 --vtk-filename foo --vtk-write-frequency 1 --iterations 10
```
| Branch  |  Seconds for VTK | % of Sim  |
|---|---|---|
Master | 83.394 | 90.398
replaceStdEndl | 30.968 | 76.691

Replace std endl

---

Jenkinsfile
src/autopas/utils/WrapOpenMP.h
tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.h

Non-Applicable configurations do not generate tests now.
For some reason, clang-format decided to change the indent on a large part of the file so review with hiding whitespaces
Ran the tests and they did not fail :innocent:

More N3 tests

---

src/autopas/namespaces.h
src/autopas/selectors/AutoTuner.h
src/autopas/selectors/Smoothing.cpp
src/autopas/selectors/Smoothing.h
src/autopas/utils/Math.h
tests/testAutopas/tests/selectors/SmoothingTest.cpp
tests/testAutopas/tests/selectors/SmoothingTest.h

The dashed line represents the "reduced values" (what we used so far), the normal line the smoothed values. We can see that due to external stress on the system the reduced values spike frantically and sometimes lead to a wrong ordering. The smoothed lines are much more robust and always stay in the same vertical order.
Simulation parameters: 
`md-flexible --deltaT 0 --particle-generator uniform --cutoff 1 --box-length 10 --particles-total 20000 --traversal vlc_c01,lc_c08 --tuning-interval 10 --tuning-phases 100`

Evidence smoothing

---

cmake/modules/vectorization.cmake
src/autopas/molecularDynamics/LJFunctorAVX.h

Made AutoPas run on my Raspberry Pi4 4GB with an aarch64 kernel. These are the changes that were necessary.

Compatibility arm64

---

examples/md-flexible/src/parsing/MDFlexConfig.cpp
src/autopas/utils/logging/TuningDataLogger.cpp
src/autopas/utils/logging/TuningResultLogger.cpp

Since this logger only writes once per tuning phase there is no significant (or measurable) performance drop.

Flush logger always

---

examples/md-flexible/CMakeLists.txt
examples/md-flexible/scripts/measurePerf.sh
examples/md-flexible/src/Simulation.h
examples/md-flexible/src/parsing/CLIParser.cpp
examples/md-flexible/src/parsing/MDFlexConfig.cpp
examples/md-flexible/src/parsing/MDFlexConfig.h
examples/md-flexible/src/parsing/YamlParser.cpp

When number of iterations is only an estimate:
When number of iterations is known exactly:

Progress Bar

---

examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/Simulation.h

Added a Suffix to the AUTOPAS_LOG and .vtk files in md-flexible, if AUTOPAS_MPI is enabled.
The Suffix describes to which MPI rank the files belongs.
The Suffix should only be added when AUTOPAS_MPI is enabled and should correspond to the number of ranks.

MPI_rank Suffix

---

examples/md-flexible/src/Simulation.cpp

To ensure that the function "calculateHomogeneity" does not return "inf" in certain but otherwise normal cases, it was necessary to ensure that for the calculation of "densityPerCell" no value is divided by zero.

Homogeneity not inf

---

src/autopas/AutoPas.h
src/autopas/selectors/AutoTuner.h
tests/testAutopas/tests/selectors/AutoTunerTest.cpp

Add a trigger to force restart of the tuning process upon the next call to `iteratePairwise()`

Force retune

---

.lgtm.yml
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCSlicedTraversal.h
src/autopas/selectors/AutoTuner.h
tests/testAutopas/tests/selectors/AutoTunerTest.cpp
tests/testAutopas/tests/selectors/AutoTunerTest.h

Difficult to test. AutoTuner is one big state machine that does not allow to simply add measurements + actual tuning.

Fix Smoothing Bugs

---

tests/testAutopas/tests/containers/TraversalComparison.cpp

deactivate traversalComparisonTests for `globals == false` since it does not add any debugging information which globals == true does not already.
This reduces the amount of generated tests significantly and should speed up testing.

deactivate traversalComparisonTests for globals == false

---

src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/containers/verletListsCellBased/verletLists/traversals/VLTraversalInterface.h
src/autopas/molecularDynamics/MoleculeLJ.h
src/autopas/particles/ParticleBase.h
src/autopas/sph/SPHParticle.h
tests/testAutopas/testingHelpers/NonConstructibleParticle.h

- Make generic `Particle::get()` `const`
- ~needs `const` cast on this ptr as we use it non-const~
- Introduce non-const getter for this
Although the second point seems a bit hacky the overall result seems to be more const-correct than before.

Generic Particle::get() const

---

cmake/modules/autopas_mpi.cmake
examples/md-flexible/CMakeLists.txt
examples/md-flexible/tests/CMakeLists.txt
examples/sph-mpi/CMakeLists.txt
src/autopas/CMakeLists.txt

Cleanup of MPI linkings:
- merges into #597. If the former is merged into master before this one was merged (which I would be ok with) we need to point this one to master.
NOT YET! @J0llyver please test this and tick the box when you have.

Cleanup of MPI linkings

---

Jenkinsfile

Aborts an old job if a new job is scheduled.
Now old jobs will be aborted with a message like:
```
Superseded by AutoPas-Multibranch/PR-647#4
```
See:
https://vmbungartz21.in.tum.de/blue/organizations/jenkins/AutoPas-Multibranch/detail/PR-647/3/pipeline

[CI] Abort old jobs

---

examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp
examples/md-flexible/tests/domainDecomposition/DomainToolsTest.cpp
examples/md-flexible/tests/domainDecomposition/DomainToolsTest.h
examples/md-flexible/tests/domainDecomposition/RegularGridDecompositionTest.cpp
examples/md-flexible/tests/domainDecomposition/RegularGridDecompositionTest.h
examples/md-flexible/tests/domainDecomposition/TestRegularGridDecomposition.cpp
examples/md-flexible/tests/yamlTestFiles/haloParticleTest.yaml
examples/md-flexible/tests/yamlTestFiles/particleExchangeTest.yaml

Halo- and Migrating-Particle-Exchange have been fixed (2d -> 3D)
Created tests to properly test the particle exchange.
default md-flexible run now has correct amount of halo particles
Manual test run on cluster with 27 ranks with fallingDrop scenario with 90000 iterations.
Ran all mdFlexTests

Md flex/halo particle fix

---

cmake/modules/autopas_mpi.cmake
examples/md-flexible/README.md

Removes the requirement to use bote Cmake variables AUTOPAS_INCLUDE_MPI and MD_FLEXIBLE_USE_MPI to properly build MD-Flexible with MPI.
This has been tested by removing the build folder and by rebuilding only using the MD_FLEIXBLE_USE_MPI variable.
The build was successful, the fallingDrop scenario ran without issues on 4 ranks. All tests in mdFlexTests were successful

add missing cmake variable

---

examples/md-flexible/src/ParallelVtkWriter.cpp
examples/md-flexible/src/ParallelVtkWriter.h
examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/configuration/MDFlexConfig.cpp

Removed unecessary content name in simulation record files.
Limited output of some simulation data to a single rank.
This has been tested by generating a new checkpoint and afterwards loading it.
Also the mdFlexTests have been executed.

Removed content name in vtk writer and limited output to single rank

---

src/autopas/containers/octree/Octree.h
src/autopas/containers/octree/OctreeInnerNode.h
src/autopas/containers/octree/OctreeLeafNode.h
src/autopas/containers/octree/OctreeNodeWrapper.h
src/autopas/containers/octree/OctreeStaticNodeSelector.h

The `forEach` and `reduce` methods were only dummy functions in the `Octree` class. Now they are implemented using proper in-place iterators.

Better Iterators for Octree

---

.github/workflows/TestSuites.yaml

`make clangformat && git status` yields no changes so currently everything is clean and the test should pass.

Include examples folder in formatting checks

---

examples/md-flexible/input/fallingDrop.yaml

Changing fallingDrop.yaml to take advantage of reflective boundaries. In addition the default verlet-skin-radius was increased to limit the number of particles being lost (likely from moving too quickly past the reflective boundaries) and increase realism. 
Finally some changes to several other fields were made - these were from personal preference and I am happy to revert them to the original.
Is only an input file.

Falling drop with reflective boundaries

---

src/autopas/molecularDynamics/LJFunctorSVE.h

The `__attribute__` accepted both by `fcc` and `gcc`.

Force SVE Kernel inline

---

.github/workflows/TestSuites.yaml
examples/md-flexible/CMakeLists.txt
examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/Simulation.h
examples/md-flexible/src/templateInstantiations/iteratePairwiseLJFunctor.cpp
examples/md-flexible/src/templateInstantiations/iteratePairwiseLJFunctorAVX.cpp
examples/md-flexible/src/templateInstantiations/iteratePairwiseLJFunctorGlobals.cpp
examples/md-flexible/src/templateInstantiations/iteratePairwiseLJFunctorSVE.cpp
src/autopas/molecularDynamics/LJFunctorAVX.h
src/autopas/molecularDynamics/LJFunctorSVE.h

Currently, we always compile all functors for MD-Flexible. This PR introduces mechanisms to choose which ones to compile to reduce compile time and memory consumption.

Avoid Compiling Uninteresting Functors

---

src/autopas/utils/WrapMPI.h

Copy old_communicator to the location of new_communicator instead of pointing new_communicator to a temporary
I'm actually surprised the previous version didn't lead to segfaults.

WrapMPI bugfix

---

examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.h
examples/md-flexible/tests/domainDecomposition/MixedBoundaryConditionTest.cpp
examples/md-flexible/tests/domainDecomposition/MixedBoundaryConditionTest.h
examples/md-flexible/tests/domainDecomposition/ReflectiveBoundaryConditionTest.cpp
src/autopas/molecularDynamics/ParticlePropertiesLibrary.h

Replaces the existing reflecting boundary mechanism with one based on mirror particles. Here 'mirror' particles are placed on the opposite side of a reflecting boundary from an original particle, and the two interact via the standard Lennard-Jones functor. Interactions are limited to when particles are within a range such that any LJ interaction leads to repulsion only.

Mirror particles for reflecting

---

examples/md-flexible/input/AllOptions.yaml
examples/md-flexible/src/configuration/MDFlexConfig.cpp

Using AllOptions.yaml file as input for md-flexible used to throw errors.
- Correct `particle-type` ordering
- Turn on Brownian Motion to avoid 0 velocities
- Reduce the timestep
- Add ClosestPackedCube objects to the output
Ran the md-flexible simulation and visualized in paraview:

Fix MD-flexible example

---

examples/md-flexible/src/configuration/objects/CubeClosestPacked.h
examples/md-flexible/src/configuration/objects/Object.h
examples/md-flexible/tests/ParticlePropertiesLibraryTest.cpp
examples/md-flexible/tests/configuration/GeneratorsTest.cpp
examples/md-flexible/tests/configuration/MDFlexConfigTest.cpp
examples/md-flexible/tests/yamlTestFiles/cubeClosestPacked.yaml
examples/md-flexible/tests/yamlTestFiles/multipleObjectsWithMultipleTypesTest.yaml
tools/autopasTools/generators/ClosestPackingGenerator.h

- Add `getParticlesTotal()` for cubeClosestPacked 
- Add cubeClosestPacked object to md_flexible tests
Calculation has been tested with all combinations of odd or even rows, columns, layers
`xNumRow` = 4
`xOdd` = true, da insgesamt 7 x-Positionen
`yNumEven` = 4 (dunkelblaue, vorderste layer)
`yNumOdd` = 3 (hellblauere, hintere layer)

Extend cubeClosestPacked for md_flexible

---

cmake/modules/autopas_all.cmake
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.h
libs/CMakeLists.txt

The CMake option for ALL is only relevant for md-flex. Rename it as to reduce confusion.

AUTOPAS_ENABLE_ALLLBL -> MD_FLEXIBLE_ENABLE_ALLLBL

---

.github/workflows/TestSuites.yaml
.github/workflows/doxygen.yaml

There is a deprecation warning to update this GitHub actions action. We also did this in ls1.

update actions/checkout@v2 -> v3

---

examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp
src/autopas/AutoPasDecl.h
src/autopas/AutoPasImpl.h
src/autopas/LogicHandler.h
src/autopas/cells/FullParticleCell.h
src/autopas/cells/ParticleCell.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/containers/verletListsCellBased/varVerletLists/VarVerletLists.h
src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
src/autopas/selectors/AutoTuner.h
src/autopas/utils/ParticleCellHelpers.h
tests/testAutopas/tests/autopasInterface/AutoPasAllContainersTest.cpp
tests/testAutopas/tests/autopasInterface/AutoPasAllContainersTest.h

Utility functions to remove loops over `addParticle()`.
- ensures reserve is called every time.
- Builds upon #724 
- new tests

Add particles in bulk

---

README.md
tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianProcessTest.h

After updating the compiler versions in our docker containers, some `GaussianProcessTest`s fail. This is only because they use very few samples in order to keep runtime as low as possible. This PR adjusts the numbers so that the tests pass again.
CI

Fix GaussianProcess Tests

---

src/autopas/AutoPasImpl.h
src/autopas/namespaces.h
src/autopas/utils/CompileInfo.cpp
src/autopas/utils/CompileInfo.h

Always print the name and version of the used compiler together with the autopas version.
Tries to use the generally available `__VERSION__` macro and adds further information if the output is insufficient.
Tested compilers:
Compiled md-flex and looked at the output.

Compiler info

---

examples/md-flexible/CMakeLists.txt
src/autopas/molecularDynamics/LJFunctorAVX.h

LJFunctoAVX::SoAFunctorVerlet had a race condition and we had no test to detect it.
- builds on top of #709

Fix race conditions

---

src/autopas/selectors/AutoTuner.h

When we resize the container also adapt the number of spacial locks.
- fix for bug introduced via #712

Adapt number of spacial locks at resize

---

examples/md-flexible/input/AllOptions.yaml
examples/md-flexible/src/configuration/MDFlexConfig.cpp

- The md-flex end-config has so far printed in integer value for the log level. Now a string representation is printed.
- Comment for AllOptions.yaml added, which points to the description of parameters
- If an end-config is used as input, the correct log level from the end-config-yaml is used.
- fixes #706
All existing tests

correct md-flex log level output in endconfig

---

src/autopas/containers/verletClusterLists/VerletClusterLists.h

- Some buffer allocations in the begin() and getRegionIterator() functions could be removed since _particlesToAdd contains only particles in rebuild iterations. So in all non-rebuild iterations the additionalVectors can be passed directly to the ContainerIterator without concatenating them with _particlesToAdd.
- Description added why it is (at the moment) necessary to keep the _particlesToAdd buffer-structure for VCL.
- All existing tests

Remove unnecessary buffer allocations in VCL

---

src/autopas/containers/verletClusterLists/VerletClusterLists.h

It looks like the problem came from the fact that we called `particlesToAddEmpty()` in iterations with invalid container status. However, in these iterations `_particlesToAdd` is used by multiple threads, which is why races can occur. In this version, we solve this by calling `particlesToAddEmpty()` only when the container state is valid, to ensure that we don't have particles in the buffer during these iterations:
```c++
if (_isValid != ValidityState::invalid) {
// This section ensures that we do not have particles in _particlesToAdd when the container status is valid. 
// In this case we don't need to concatenate the buffers, we can just pass the additionalVectors.
if (not particlesToAddEmpty()) {
autopas::utils::ExceptionHandler::exception(
"VerletClusterLists::begin(): Error: particle …
```

Bugfix for race condition in VCL

---

examples/md-flexible/src/Simulation.cpp
src/autopas/molecularDynamics/LJFunctorSVE.h
tests/testAutopas/tests/molecularDynamics/LJFunctorSVETest.cpp

- SVE functor now compiles with two minor fixes.
- SVE AoS functor correctly calculates globals now
- SVE SoA functor single correctly applies forces by always calling the SoAKernel with newton3=true.

Fixing LJFunctorSVE

---

README.md
src/autopas/LogicHandler.h
src/autopas/iterators/ContainerIterator.h
tests/testAutopas/tests/iterators/ContainerIteratorTest.cpp
tests/testAutopas/tests/iterators/ContainerIteratorTest.h
tests/testAutopas/tests/iterators/IteratorTestHelper.h

Reversing the assignment of buffers to iterators during iteration caused race conditions.
- bug introduced here: #712
No issue was created.

Unreverse buffers

---

examples/md-flexible/src/configuration/MDFlexConfig.cpp
examples/md-flexible/src/configuration/objects/Object.h

Running the generated `yaml` files does not work. This PR reolves this.
- Changes introduced here: #682 
```bash
./md-flexible                                     # this generates a yaml file
./md-flexible --yaml-filename MDFlex_end_*.yaml   # this call should not fail
```

Fix generated yaml files

---

cmake/modules/autopas_antlr4cpp.cmake
src/autopas/tuning/AutoTuner.cpp
src/autopas/utils/RaplMeter.cpp
src/autopas/utils/RaplMeter.h

- The RaplMeter::init() does not throw exceptions if energy measurement is not available but an error string.
- ~The warnings in AutoTuner were replaced by `INFO` outputs without the error message, if energy measurement is not strictly needed.~
- In autopas_antlr4cpp.cmake `DEPENDS` is added again, otherwise utf8cpp might be downloaded from github in antlr's cmake files if we build for example with `make -j16`. (this was somehow removed from #780 during merge)

Dont throw if energy measurement is unavailable

---

examples/md-flexible/src/configuration/CLIParser.cpp

`loadEstimatorOptions` was missing from `MDFlexConfig::relevantOptions`. Thus it was not included in zsh completions and help messages.

Add loadEstimatorOptions to Relevant Options

---

src/autopas/pairwiseFunctors/CellFunctor.h
src/autopas/particles/OwnershipState.h
tests/testAutopas/tests/pairwiseFunctors/CellFunctorTest.cpp
tests/testAutopas/tests/pairwiseFunctors/CellFunctorTest.h

All containers do too many unnecessary halo-halo interactions. This PR tries to lower the amount of these interactions. A complete elimination seems too much effort at this point but anything that can be ignored due to knowledge about the layout of the domain and container should be ignored.
- only possible thanks to #745

Less Halo Halo Interactions

---

src/autopas/containers/linkedCells/LinkedCellsReferences.h
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.h

This PR should fix the bug described in #791.
In `LinkedCellsReferences::updateContainer()`, the halo particles were deleted with `deleteHaloParticles()` before all leaving particles were detected. This function deletes all halo particles in the data structure that stores the actual particles (`_particleList`). However, as a result, the references in the cells that point to the particles in `_particleList` are no longer correct. 
One solution would be to make a call to `updateDirtyParticleReferences()` directly after deleting the halo particles. However, since `_particleList` contains owned particles that have already been moved to the halo area, an exception is thrown when assigning the particles to the halo cells. So the simplest solution is to first run the loop that filters out all …

LinkedCellsReferencesFix

---

examples/md-flexible/src/TimeDiscretization.cpp
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp
src/autopas/LogicHandler.h
src/autopas/containers/LeavingParticleCollector.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/linkedCells/LinkedCellsReferences.h
src/autopas/containers/octree/Octree.h
src/autopas/containers/verletClusterLists/ClusterTowerBlock2D.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/iterators/ContainerIterator.h
src/autopas/particles/OwnershipState.h
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp

Especially the following unit tests check that regions work correctly:
```yaml
verlet-rebuild-frequency         :  15
verlet-skin-radius-per-timestep  :  0.2
selector-strategy                :  Fastest-Absolute-Value
data-layout                      :  [SoA]
traversal                        :  [lc_c08]
functor                          :  Lennard-Jones (12-6) AVX intrinsics
newton3                          :  [enabled]
cutoff                           :  2.5
cell-size                        :  [1]
deltaT                           :  0.0001
iterations                       :  50
boundary-type                    :  [periodic, periodic, periodic]
box-min                          :  [-70,-70,-70]
box-max                          :  [70, 70, 70]
Objects:
CubeGrid:
0:
particles-per-dimension …
```

Parallelize LeavingParticleCollector

---

src/autopas/containers/verletClusterLists/traversals/VCLC01BalancedTraversal.h

This PR should solve a bug with the `VCLC01BalancedTraversal`.
To reproduce the bug, run the test `testAllConfigurations` with >= 6 threads using commit 06a9fd21a5219987d0bf121e79cd9a2c37bf6b3d.
The problem is the check `clusterCount < clusterRange.numClusters` in `VCLC01BalancedTraversal::traverseParticlePairs` in the parallel region:
https://github.com/AutoPas/AutoPas/blob/06a9fd21a5219987d0bf121e79cd9a2c37bf6b3d/src/autopas/containers/verletClusterLists/traversals/VCLC01BalancedTraversal.h#L77-L84
This check therefore fails if `clusterIndex`, which is initially set to `startIndexInTower`, is smaller than `clusterRange.numClusters`. This becomes a problem if a thread is assigned clusters from two towers, for example, and the `startIndex` in the first tower is already greater than …

Bugfix for VCLC01BalancedTraversal

---

.github/CONTRIBUTING.md
README.md

The Problem: Links in markdown files should work both in doxygen, the doc webpage, and on github.
Internal links don't work reliably on the webpage, hence all markdown files that are directly included in doxygen directly should use https links.
Repo-abolute paths in the documentation pages

Nicer Links in Docs

---

src/autopas/containers/CellBlock3D.h
src/autopas/containers/ParticleContainerInterface.h
tests/testAutopas/tests/containers/CellBlock3DTest.cpp

Fixes the value clamping in `CellBlock3D::getCellBoundingBox()` when we calculate the bounding box of a cell at the lower edge of the domain.
- This caused the particle duplication bug in ls1 because particles were not found by the `LeavingParticleCollector`. Thus during the update, some halos were not removed and their corresponding owned partners were placed right on top of them.
- *Why was this not an issue before?* Not sure. I think when I rewrote the Iterators in #712 I started using `CellBlock3D::getCellBoundingBox()` significantly more than it was used previously. Later when I rewrote `LeavingParticleCollector` in #792 this was used even more, especially around domain borders. So maybe we just didn't use the function for these edge cases before? Seems like another important …

Fix CellBlock3D::getCellBoundingBox()

---

.github/workflows/DocTagChecker.yaml
.github/workflows/TestSuites.yaml
.github/workflows/doxygen.yaml

Currently, DocTagChecker is a job in the Doxygen workflow. This is a problem, because this workflow is also triggered on pushes to master which doesn't make sense for DocTagChecker.
The result is that it appears as if our pipeline crashes on master.
Move DocTagChecker to separate workflow with more restrictive triggers.
- DocTagChecker was introduced here: #809 
See status of checks here

Separate DocTagChecker Workflow

---

src/autopas/options/ContainerOption.h

VVL has a bug which keeps on cropping up (see #721 ). As far as I am aware, there are no major problems from using this container except that the tuner might select it without it being optimal. Without a fix, this container should at the very least be discouraged.
Also, I do not see why Verlet Cluster Lists are discouraged.

Make VCL no longer discouraged and make VVL discouraged

---

.github/workflows/TestSuites.yaml
applicationLibrary/CMakeLists.txt

Refactor creation of mdLib test targets
Check CI build and run output to confirm:

Only build matching mdLib tests

---

.github/workflows/TestSuites.yaml
src/autopas/options/ExtrapolationMethodOption.h
src/autopas/tuning/tuningStrategy/PredictiveTuning.cpp
src/autopas/tuning/tuningStrategy/PredictiveTuning.h
tests/testAutopas/tests/tuning/tuningStrategy/PredictiveTuningTest.cpp

This PR adds an option to use the last traversal time as an estimate for the upcoming iterations to predictive tuning.
Added the new extrapolation method to the existing tests for predictive tuning.

Last result as extrapolation method

---

src/autopas/AutoPasDecl.h

Added a getter function for `tuningMetric` in `AutoPasDecl.h` to access it from ls1-mardyn. A getter function is available in `AutoTuner.cpp` but cannot be directly accessed from there. 
Only a getter function added, no effect on any tests or simulation pipeline.

Adding getter for tuningMetric in Autopas class to access from ls1-mardyn

---

src/autopas/LogicHandler.h
src/autopas/containers/CellBasedParticleContainer.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/linkedCells/LinkedCellsReferences.h
src/autopas/containers/octree/Octree.h
src/autopas/containers/verletClusterLists/ClusterTowerBlock2D.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
tests/testAutopas/tests/iterators/RegionParticleIteratorTest.cpp
tests/testAutopas/tests/iterators/RegionParticleIteratorTest.h

Region iterators do not consider particles that are in the region but are stored in cells that are completely outside the region. This affects all containers.
- noticed in #826 
The following scenario with 179800 particles was used for the performance comparison with 8 HW threads:
```
./md-flexible --container LinkedCells --functor Lennard-Jones-AVX2 --traversal lc_c01 --newton3 disabled --data-layout AoS --verlet-rebuild-frequency 10 --verlet-skin-radius-per-timestep 0.025 --cutoff 2.5 --cell-size 1 --deltaT 0.001 --iterations 2000 --boundary-type reflective --fastParticlesThrow true --particle-generator closest --box-length 50 --particle-spacing 1.0 --no-progress-bar true
```
Since `getRegionIterator` is called in `updateContainer` and `reflectParticlesAtBoundaries`, the times were …

Fix Region Iterators

---

applicationLibrary/molecularDynamics/molecularDynamicsLibrary/MoleculeLJ.h
examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/configuration/MDFlexConfig.h
src/autopas/LogicHandler.h
src/autopas/containers/linkedCells/LinkedCellsReferences.h
src/autopas/options/Option.h
src/autopas/tuning/AutoTuner.cpp
src/autopas/tuning/AutoTuner.h
src/autopas/utils/ArrayMath.h
src/autopas/utils/RaplMeter.cpp
src/autopas/utils/RaplMeter.h

A bunch of small but not necessarily minor fixes:

Small Fixes

---

cmake/modules/autopas_logging.cmake
src/autopas/AutoPasImpl.h
src/autopas/LogicHandler.h
src/autopas/containers/LoadEstimators.h
src/autopas/containers/ParticleContainerInterface.h
src/autopas/containers/linkedCells/traversals/LCC04Traversal.h
src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.h
src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsGeneratorFunctor.h
src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsNeighborList.h
src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCCellPairNeighborList.h
src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCNeighborListInterface.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCC01Traversal.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCC18Traversal.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCCellPairC08Traversal.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCSlicedBalancedTraversal.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCSlicedC02Traversal.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCSlicedTraversal.h
src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCTraversalInterface.h
src/autopas/iterators/ContainerIterator.h
src/autopas/options/TraversalOption.h
src/autopas/tuning/AutoTuner.cpp
src/autopas/tuning/selectors/ContainerSelector.h
src/autopas/utils/logging/IterationLogger.cpp
src/autopas/utils/logging/Logger.h
src/autopas/utils/logging/PredictionLogger.cpp
src/autopas/utils/logging/TuningDataLogger.cpp
src/autopas/utils/logging/TuningDataLogger.h
tests/testAutopas/tests/containers/verletListsCellBased/verletListsCells/PairwiseVerletListsTest.h
tests/testAutopas/tests/containers/verletListsCellBased/verletListsCells/VerletListsCellsTest.cpp

Collection of annoyances I stumbled upon while reading the code.

More Small Fixes

---

src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/linkedCells/LinkedCellsReferences.h
src/autopas/containers/octree/Octree.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h

There was a wrong calculation for the box with safety margin in the LinkedCells iterator.
- Bug was introduced in PR #830

Fix bug that broke exploding liquid

---

src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.cpp
src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.h

When AutoPas is compiled with Clang and without RuleBasedTuining, the compiler complains about some unused variables.
Please include a summary of the changes.
- #866

Refactor RuleBasedTuning class to avoid unused variable warnings.

---

applicationLibrary/CMakeLists.txt
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonFunctor.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/Parameters.h

Related issue: [886](https://github.com/AutoPas/AutoPas/issues/886)
What has been done:
- removed anything related to mixing (i.e. `useMixing` and `_PPLibrary` ) as this Functor is specific to Argon particles
- added the parameters $A$, $\alpha$, $Z$ and $\beta$ as `static constexpr std::array` private members of ArgonFunctor
- added `getIndex` to retrieve the correct array index based on (i, j, k) and throw `AutoPasException` for 'illegal' access

Parameters argon functor

---

examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/Simulation.h
src/autopas/LogicHandler.h
src/autopas/utils/SimilarityFunctions.h
src/autopas/utils/ThreeDimensionalMapping.h
tests/testAutopas/tests/utils/SimilarityFunctionsTest.cpp

Fixes `calculateHomogeneityAndMaxDensity` and adds a test for it.
Previously, `calculateHomogeneityAndMaxDensity` assumed that the domain started at (0,0,0) when indexing particles into bins. Furthermore, the algorithm was sub optimal and the code was messy.
This PR:
- #PR #876 highlighted the issue

Fix calculate homogeneity and max density

---

src/autopas/containers/CellBlock3D.h

All actual code changes are inside of `getNearbyHaloCells()`.

Make getNearbyHaloCells reserve

---

docs/userdoc/CustomApplications.md
docs/userdoc/Iterators.md
docs/userdoc/Logging.md
docs/userdoc/SimulationLoop.md
src/autopas/AutoPasDecl.h

Change Markdown Code language tags from `cpp` to `c++`:
- Github supports both styles, there it doesn't matter
- CLion only supports c++
Looked at rendered markdown files with C++ code in them on:

Change Markdown Language Tags from cpp to c++

---

src/autopas/CMakeLists.txt
src/autopas/pairwiseFunctors/CellFunctor.h
src/autopas/utils/DataLayoutConverter.h
src/autopas/utils/MemoryProfiler.cpp
src/autopas/utils/MemoryProfiler.h
tests/testAutopas/tests/utils/LoggerTest.h

_Finally, the update nobody asked for 🙃_
- Compilation/ MD-Flexible/ Testing works now on macOS using Apple Clang and GCC Compilers
- Update `CMakeList.txt` with a generator expression that enables  the `rt` library depending on whether you use macOS or Linux. The library is not available on macOS, but it is also not needed to access the `Time.h` header!
-  Add `<algorithm>` in `LoggerTest.h` due to the usage of `std::clamp` - some compilation problem which probably has not yet appeared before due to nondeterministic compilation, but happened on my machine
- Fixes implicit conversion for `Apple Clang` in `CellFunctor.h` and `DataLayoutConverter.h` by introducing a `static_cast` 
- I am not certainly sure why `Apple Clang` complains about the current usage of the `DataLayoutOption` with …

Fix MacOS Compliance

---

applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/Legendre.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/RepulsiveTerm.h
src/autopas/utils/ArrayMath.h
tests/testAutopas/tests/utils/ArrayMathTest.cpp

Added `operator*(T s, const std::array<T, SIZE> &a)` which returns same result as `operator*(Tconst std::array<T, SIZE> &a, T s)`.

Extending array math

---

examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/Simulation.h

MD-flexible added the global forces to the particles twice. Once in `TimeDiscretization::calculatePositionsAndResetForces` and once in `updateForces`.
The addition of the global forces in `updateForces` has been removed, as `TimeDiscretization::calculatePositionsAndResetForces` iterates over the particles in a loop anyway. This saves further iteration over the particles in `updateForces`.
To make the names of the functions a little more intuitive, `Simulation::updatePositions` has been renamed `Simulation::updatePositionsAndResetForces`. `Simulation::updateForces` has been renamed `Simulation::updateInteractionForces`.
Since we do not have access to the timers in `TimeDiscretization::calculatePositionsAndResetForces`, the timer for setting the global forces has been removed.

Remove global force reset from updateForces

---

applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctor.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorAVX.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorSVE.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJMultisiteFunctor.h
applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorFlopCounterTest.cpp
applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestGlobals.cpp

Previously, when calculating globals, we had a differentiation of newton3 and non-newton3 cases. This seemed unnecessarily complicated and made it difficult to correctly count flops in case of enabled globals. (see #850)
The new implementation adds a full contribution of the virial and the energy for each owned particle. The sums are divided by 2 in the post processing step in `endTraversal()`.
This also reduces the number of flops in the `newton3` case as division by 2 is done only once in the post processing.
[ls1_only.log](https://github.com/user-attachments/files/16414991/ls1_only.log)
[old_autopas.log](https://github.com/user-attachments/files/16414992/old_autopas.log)
[refactored_autopas.log](https://github.com/user-attachments/files/16414993/refactored_autopas.log)

Refactor calculation of globals

---

applicationLibrary/molecularDynamics/tests/singleSiteTests/ForceCalculationTest.cpp
tests/testAutopas/testingHelpers/commonTypedefs.h
tests/testAutopas/tests/containers/linkedCells/traversals/SlicedTraversalTest.cpp

When `AUTOPAS_LOG_FLOPS=OFF` the test `SlicedTraversalTest.testTraversalCubeShrink` fails. This went unnoticed because our CI only tests with the logging enabled.
The CMake Parameter and new FLOP counting mechanic was introduced in #850

Fix FLOP counting in Tests

---

examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp

This PR aims to fix an issue with adding halo particles in MPI runs.
The problem was solved by removing the double addition of the `skinWidth*rebuildFrequency` from `boxMin` and `boxMax` in the `RegularGridDecomposition::collectHaloParticlesForLeftNeighbor` abd `RegularGridDecomposition::collectHaloParticlesForRightNeighbor`. This is now done in the `getParticleImpl` functions of the containers.
All existing tests.

MPI Bugfix Halo Box

---

applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/AngularFunctions.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/CosineHandle.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/DampingTerm.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/DispersionTerm.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/ArgonInclude/Legendre.h

Fixed:
- `sin_theta_derive_wrt(CosineHandle cosine)` when derivative of cosine = (0, 0, 0)
- `CosineHandle::derive_wrt()` -> using L2Norm for denominators instead of cdot (order of vectors does not matter)
- damping term derivative -> summation term
- missing - sign in force from dispersion term
- derivative of Legendre Polynomial
- derivative of W calculations (* instead of + in denominator)
- derivative of sin_theta (divide by 0)

Bug fixes to force calculation

---

src/autopas/containers/verletClusterLists/VerletClusterListsRebuilder.h

This PR is intended to fix a bug with the Verlet Cluster Lists. 
Particles were not sorted into the correct towers when recreating the neighborlists. The problem was that the order in which out-of-bound particles of the tower were collected and the resizing of the towerblock was wrong. The out-of-bound particles were collected first, then the tower block (and thus also the bounding boxes of the tower) were recalculated. However, the out-of-bounds particles should be collected only after the new tower bounding boxes have been calculated.
The scenario from #917 with a single thread was used. The results for VCL and linked cells were compared (particle interactions and resulting forces). A python script was used that calculates …

Verlet Cluster Lists Bugfix

---

src/autopas/tuning/AutoTuner.cpp
src/autopas/tuning/tuningStrategy/ActiveHarmony.cpp
src/autopas/tuning/tuningStrategy/ActiveHarmony.h
src/autopas/tuning/tuningStrategy/BayesianClusterSearch.cpp
src/autopas/tuning/tuningStrategy/BayesianClusterSearch.h
src/autopas/tuning/tuningStrategy/BayesianSearch.cpp
src/autopas/tuning/tuningStrategy/BayesianSearch.h
src/autopas/tuning/tuningStrategy/MPIParallelizedStrategy.cpp
src/autopas/tuning/tuningStrategy/MPIParallelizedStrategy.h
src/autopas/tuning/tuningStrategy/PredictiveTuning.cpp
src/autopas/tuning/tuningStrategy/PredictiveTuning.h
src/autopas/tuning/tuningStrategy/RandomSearch.cpp
src/autopas/tuning/tuningStrategy/RandomSearch.h
src/autopas/tuning/tuningStrategy/SlowConfigFilter.cpp
src/autopas/tuning/tuningStrategy/SlowConfigFilter.h
src/autopas/tuning/tuningStrategy/SortByName.cpp
src/autopas/tuning/tuningStrategy/SortByName.h
src/autopas/tuning/tuningStrategy/TuningStrategyInterface.h
src/autopas/tuning/tuningStrategy/TuningStrategyLogger.cpp
src/autopas/tuning/tuningStrategy/TuningStrategyLogger.h
src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.cpp
src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.h

As described in #894, some tuning strategies, like Random or Bayesian strategies, want to terminate tuning after a given number of samples has been collected. They do this by flushing the config queue.
Until now, however, this flushing was reset by the config wipe checker.
An optional flag (`intentionalConfigWipe`) has been introduced to indicate that the config wipe was intentional and the config wipe checker does not reset the queue. 
The scenario in #894 was used to test the behavior. Instead of the 20/20 tuning iterations it does now 4/20 tuning iterations.
```
md-flexible \
--tuning-strategies random-Search \
--tuning-max-evidence 2 \
--tuning-samples 2 \
--iterations 20 \
--no-flops \
--no-end-config
```

Tuning Strategy Config Wipe Fix

---

src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.cpp

#936 changed `TuningStrategyInterface` functions to return a `bool`. For one return call it was missed to add a return value. This PR fixes this.
- #936 
- compiled without warning.

HOTFIX: Add missing return value

---

src/autopas/tuning/Configuration.cpp

Revised regex patterns in IterationLogger to use escape characters for `{` and '}'. This is required by Apple Clang 15.0.0

Update Regex Pattern

---

examples/md-flexible/input/SpinodalDecomposition_equilibration.yaml
examples/md-flexible/input/explodingLiquid.yaml
examples/md-flexible/src/ParallelVtkWriter.cpp
examples/md-flexible/src/ParticleSerializationTools.cpp
examples/md-flexible/src/Simulation.cpp
examples/md-flexible/src/Simulation.h
examples/md-flexible/src/configuration/MDFlexConfig.cpp
examples/md-flexible/src/configuration/MDFlexConfig.h
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp
examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.h
examples/md-flexible/src/main.cpp
examples/md-flexible/tests/configuration/GeneratorsTest.cpp
src/autopas/AutoPasImpl.h
src/autopas/LogicHandler.h
src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.cpp
src/autopas/utils/ArrayMath.h
src/autopas/utils/Math.cpp
src/autopas/utils/Math.h
tests/testAutopas/tests/iterators/RegionParticleIteratorTest.cpp
tests/testAutopas/tests/utils/MathTest.cpp

Fix Loading MPI Checkpoints

---

.github/workflows/TestSuites.yaml

Switch to a new version (v0.18.2) of clang-format-lint-action to fix the style checker.

Fix Clang Format

---

src/autopas/containers/directSum/DirectSum.h
src/autopas/containers/linkedCells/LinkedCells.h
src/autopas/containers/linkedCells/LinkedCellsReferences.h
src/autopas/containers/linkedCells/ParticleVector.h
src/autopas/containers/octree/Octree.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
src/autopas/particles/ParticleBase.h
tests/testAutopas/tests/containers/AllContainersTests.cpp
tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
tests/testAutopas/tests/containers/octree/OctreeTests.cpp
tests/testAutopas/tests/containers/verletListsCellBased/varVerletLists/VarVerletListsTest.cpp
tests/testAutopas/tests/containers/verletListsCellBased/verletLists/VerletListsTest.cpp
tests/testAutopas/tests/tuning/selectors/ContainerSelectorTestFromTo.cpp
tools/autopasTools/generators/UniformGenerator.h

Removing setting particle ownership in containers. This is now completely handled by [LogicHandler](https://github.com/AutoPas/AutoPas/commit/5d22b5c25d11d14549f580253c7969a0a7896aed) (as already updated in #931) 
- #821 (simplifies by merging this change here)

removing ownership setting in containers

---

src/autopas/tuning/tuningStrategy/LiveInfo.h

The csv from the live info logger contained whitespaces between the column head names and the ','. This is inconsistent to our other loggers and inconvenient to parse.
This PR removes the whitespaces by adapting the way the header is generated from the `toString()` method.

Strip whitespaces from LiveInfoLogger header

---

src/autopas/LogicHandler.h
src/autopas/particles/ParticleBase.h

This PR contains two main changes:
- Currently the distance check in `ParticleBase.h` in `setRDistanceCheck()` doesn't consider the case of skin=0. In that case, it always gives out a WARN statement (which affects performance if compiled with logger, even when logger is turned off at runtime). Zero skin condition is handled here.
- In `LogicHandler.h`, we already add a haloParticle to the buffer, so adding ownership again after it has been added is not needed. And so, this is removed.
- #931 ownership set in LogicHandler
Verified by running cases with zero skin.

removing distance check for zero skin case

---

src/autopas/LogicHandler.h
src/autopas/LogicHandlerInfo.h

`LogicHandler` sets up a bunch of locks for the parallelized remainder traversal between buffers and the container to avoid race conditions. The number of these locks depends on the domain size and the interaction length.
In a perfect world, we could calculate a virtual 3D grid with mesh width `interactionLength`, have one lock per grid cell and be happy. Alas, the world is shit.
If the domain is very large and/or the interaction length very small the number of locks skyrockets and allocating space for a few billion locks just is not good.
This PR introduces a mechanism to limit the number of locks in a geometry-aware way.
The limit is set to `1e6` so our usual simulations should not be affected at all. E.g. the limit is _just_ reached if your domain is `300x300x300` with a cutoff of …

Limit the Number of Spacial Locks

---

tests/testAutopas/tests/tuning/tuningStrategy/fuzzyTuning/FuzzyTuningTest.cpp

When setting `-DAUTOPAS_ENABLE_RULES_BASED_AND_FUZZY_TUNING=false`, the `runTests` target does not compile due to missing references to Fuzzy Tuning logic. (Some methods are not defined when this variable is not set)
I decided to fully take out the fuzzy tuning tests, when fuzzy tuning is not enabled.
It is still enabled and tested in our CI.
- Introduced with the addition of fuzzy tuning is #879 
- Compilation of autopas tests  works without enabling `-DAUTOPAS_ENABLE_RULES_BASED_AND_FUZZY_TUNING`

Disable fuzzy tests when fuzzy tuning is not enabled with CMake

---

examples/md-flexible/src/Simulation.cpp

For the potential energy of the system and the viral of the forces, the average values over the simulation run are taken into consideration by summing the global values calculated at each iteration and dividing this sum by the number of iterations at the end of the simulation.
```cpp
_potentialEnergy = (_potentialEnergy2B + _potentialEnergy3B)/_iteration;
_virial = (_virial2B + _virial3B)/_iteration;
```
where `_potentialEnergy2B `, `_potentialEnergy3B `,  `_virial2B ` and `_virial3B ` are incremented at each functor call
in `Simulation::calculatePairwiseForces` and `Simulation::calculateTriwiseForces`.
Previously, the global values were simply being summed, leading to meaningless results.

Taking AVG over simulation for global values

---

tests/testAutopas/tests/tuning/tuningStrategy/fuzzyTuning/FuzzyTuningTest.cpp

The test writes a rule file and then tries to parse it. The `ofstream` was not closed before parsing thus, it could happen that the file was not written yet. Happend [here](https://github.com/AutoPas/AutoPas/actions/runs/11295866924/job/31419527790?pr=955).

Fix `FuzzyTuningTest::testParseRuleFile()`

---

examples/md-flexible/README.md
examples/md-flexible/scripts/convertMDFlexStrucToUnstrucGrids.sh
examples/md-flexible/src/ParallelVtkWriter.cpp
examples/md-flexible/src/ParallelVtkWriter.h
examples/md-flexible/src/configuration/MDFlexConfig.cpp

The issue was that Paraview would not render surfaces of rank boxes that aren't at the outside of the full domain box (or short: inner surfaces are invisible). It turns out this is a "feature" of the `StructuredGrid`. For us, this is highly undesirable because we want to visualize all volumes. With `UnstructuredGrid` Paraview renders everything.
1. Create some output:
```bash
mpirun -n 4 md-flexible --particles-per-dimension 20 --vtk-filename foo --vtk-write-frequency 1
```
2. Check output/foo
3. Load everything into Paraview
4. ???
5. Profit

Change VTK Rank Output to UnstructuredGrid

---

examples/md-flexible/input/explodingLiquid.yaml

`verlet-skin-radius-per-timestep` in `explodingLiquid.yaml` is currently set too small leading to fast particle warnings. This pull request simply increases this value.
The new `verlet-skin-radius-per-timestep` is not heavily optimised. But `0.04` leads to fast particle warnings whereas `0.05` does not, so I changed it to `0.05`.

Adjust the `verlet-skin-radius-per-timestep` in exploding liquid to not lead to too fast particles

---

examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp
examples/md-flexible/tests/domainDecomposition/RegularGridDecompositionTest.cpp
examples/md-flexible/tests/domainDecomposition/RegularGridDecompositionTest.h

In the case of more than one MPI domain, md-flexible creates halo particles around the global boundaries, even when the boundaries are non-periodic.
This leads to wrong results, as interactions with these wrongly created halo particles will still be done.
Extended the test for halo particle exchange to test also  for boundaries `reflective` and `none`

Fix MPI halo exchange for non-periodic BCs

---

applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorSVE.h
applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestVs.cpp

Fixes compilation of SVE functor. Furthermore, it fixes tests comparing with and without PPL versions of the SVE functor by providing some margin for floating point error.

Fix SVE Functor

---

src/autopas/utils/SimilarityFunctions.h

Forces a homogeneity of 0 (i.e. a perfect homogeneity) in the case that there are no particles in a simulation domain as opposed to the previous `-nan` value.

Fixing homogeneity in zero particle scenario

---

examples/md-flexible/src/configuration/MDFlexConfig.cpp

When particles are generated on or close to the simulation box boundaries, we add some padding to avoid particles being too close to the boundary.
This can lead to confusion since the simulation has a different density than expected. I had problems with this myself and many students as well. That's why I think a warning is adequate.

Add box padding warning

---

applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctor.h
applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorAVX.h
docs/userdoc/CustomApplications.md
examples/md-flexible/src/Simulation.cpp
src/autopas/LogicHandler.h
tests/testAutopas/tests/RemainderTraversalTest.cpp

The remainder traversal for 2B always used AoS AND SoA functor calls, forcing the user to implement both. This is potentially problematic / annoying (see LADDS).
This PR introduces a mechanic that SoA is only used if the current configuration asks for it. Otherwise only AoS is used.

AoS Remiander Traversal

---

examples/md-flexible/src/Simulation.cpp

When a log filename is provided to md-flexible, this is split into a log file per rank. This makes it much easier to follow individual series of log messages for each rank, particularly when using TRACE-level logging.
If no log filename is provided, nothing is changed (all log messages are written as normal)

Rank-based splitting of md-flexible log files

---

examples/md-flexible/src/Simulation.cpp
src/autopas/LogicHandler.h
src/autopas/tuning/AutoTuner.cpp
src/autopas/tuning/AutoTuner.h
src/autopas/utils/logging/TuningDataLogger.cpp
src/autopas/utils/logging/TuningDataLogger.h

This PR includes the following changes
1. Removes the `_rebuildInterval` vector, instead uses `_numRebuilds` to keep track of number of rebuilds and estimates mean rebuild frequency using `_iteration/_numRebuilds`
2. Estimates rebuild frequency for previous simulation phase to update the autoTuner `_rebuildFrequency` which is used for weighting rebuild and non-rebuild iterations and comparing different configurations. This is achieved by keeping track of `_numRebuildsInSimulationPhase` and `_iterationAtEndOfLastTuningPhase` as ``` (_iteration - _iterationAtEndOfLastTuningPhase) /  _numRebuildsInSimulationPhase```
3. `AutoTuner::willRebuildNeighborLists()` now only triggers rebuild in tuning phase now, rebuild outside tuning phase is handled by `LogicHandler`. This was also needed as …

Dynamic rebuild frequency estimation

---

cmake/modules/autopas_pmt.cmake

If Energy Measurements are disabled, we don't need pmt. Therefore, we don't need to bother about it during CMake configuration. Saves a little bit of time and diskspace ;)

Make pmt download optional

---

.github/CONTRIBUTING.md
CMakeLists.txt
cmake/modules/autopas_all.cmake
cmake/modules/autopas_other-compileroptions.cmake
docs/userdoc/Building.md
src/autopas/containers/linkedCells/ParticleVector.h
src/autopas/containers/verletClusterLists/VerletClusterLists.h
src/autopas/utils/ExceptionHandler.h
src/autopas/utils/logging/IterationLogger.cpp
tests/testAutopas/tests/containers/octree/OctreeTests.cpp

As part of an internal collaboration with Sam, we decided that it would be a good idea to bump the C++ standard version used by AutoPas from C++17 to C++20. This PR contains the minimum set of changes to make that happen. In particular, I have updated the documentation to indicate that C++20 is used by default and fixed, with the help of Sam, some minor bugs that were causing compilation errors. 
As a side note, inside the project, there are several `@todo c++20` that are low-hanging fruit, but I would recommend that those be addressed in separate pull requests. 
- None so far
- Not any I could find
So far, I only checked that it compiled and that several tests from the CI are passing locally. I tried to run a ctest on my Mac, but (1) there are too many tests to make a full local check …

Make AutoPas use C++20
